/*
 * Copyright (C) 2010-2012 Freescale Semiconductor, Inc.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

// ---------------------------------------------------------------------
// Test Configuration
// ---------------------------------------------------------------------
#define LPM_DEFAULT_DSM_MODE 1

//#define CFG_FROM_DEFINE       1

// ---------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------
#include "common.h"
#include "registers.h"
#include "dram_api.h"
#include "config.h"
#include "low_power_mode.h"
#include "system_config.h"

void (*mx6q_suspend_t)(unsigned int mode, unsigned int addr0, unsigned int addr1) = CONFIG_FSL_MX6SL_LPM_VMA;

extern void mx6q_suspend(unsigned int mode, unsigned int addr0, unsigned int addr1);
extern config_t system_config[];
extern WORD word_field_wr(WORD cur_word, WORD field, WORD start, WORD length);
extern WORD word_field_rd(WORD cur_word, WORD start, WORD length);

// ---------------------------------------------------------------------
// Registers
// ---------------------------------------------------------------------
// SCU registers (partial)
#define SCU_CNTRL_OFFSET      0x0
#define SCU_CONFIG_OFFSET     0x4
#define SCU_CPU_PSR_OFFSET    0x8

#define SUSPEND_OCRAM_BASE    0x00918000
#define SUSPEND_OCRAM_PADDR   0x00918000

#define PAGE_TABLE_ADDR       0x0091C000
#define STRONGLY_ORDERED      0x00000DE2
#define OUTER_INNER_WB_WA     0x00005DE6

// ---------------------------------------------------------------------
// Test Configure
// ---------------------------------------------------------------------

#define RUN_MODE              0
#define WAIT_MODE             1
#define STOP_MODE             2

#define WB_COUNT              0x7

#define LPM_DSM_CFG_DEFAULT_LOW_POWER_MODE         STOP_MODE
#define LPM_DSM_CFG_DEFAULT_ARM_POWER_GATE_EN      1
#define LPM_DSM_CFG_DEFAULT_ARM_CLOCK_GATE_EN      1
#define LPM_DSM_CFG_DEFAULT_L2_POWER_GATE_EN       0
#define LPM_DSM_CFG_DEFAULT_SOC_RWB_EN             1
#define LPM_DSM_CFG_DEFAULT_OSC_POWER_DOWN_EN      1
#define LPM_DSM_CFG_DEFAULT_STANDBY_VOLTAGE_EN     1
#define LPM_DSM_CFG_DEFAULT_WEAK_2P5_EN            1
#define LPM_DSM_CFG_DEFAULT_RING_OSC_EN            1
#define LPM_DSM_CFG_DEFAULT_STOP_MODE_CONFIG       0
#define LPM_DSM_CFG_DEFAULT_RBC_EN                 1
#define LPM_DSM_CFG_DEFAULT_OSC_COUNT              0xAF
#define LPM_DSM_CFG_DEFAULT_RBC_COUNT              0x20
#define LPM_DSM_CFG_DEFAULT_STBY_COUNT             0x3
#define LPM_DSM_CFG_DEFAULT_ARM_PUP_SW             0x3F
#define LPM_DSM_CFG_DEFAULT_ARM_PUP_SW2ISO         0x3F
#define LPM_DSM_CFG_DEFAULT_RC_OSC_EN              1
#define LPM_DSM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE     0
#define LPM_DSM_CFG_DEFAULT_GPT_WAKEUP_EN          1
#define LPM_DSM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS     500
#define LPM_DSM_CFG_DEFAULT_UART_WAKEUP_EN         1
#define LPM_DSM_CFG_DEFAULT_WAKEUP_LOOP            3
#define LPM_DSM_CFG_DEFAULT_DRAM_EN                GLOBAL_DRAM_EN
#define LPM_DSM_CFG_DEFAULT_L1_CACHE_EN            GLOBAL_L1_CACHE_EN
#define LPM_DSM_CFG_DEFAULT_L2_CACHE_EN            GLOBAL_L2_CACHE_EN
#define LPM_DSM_CFG_DEFAULT_ARM_CLOCK_FREQ         800
#define LPM_DSM_CFG_DEFAULT_BUS_CLOCK_FREQ         400
#define LPM_DSM_CFG_DEFAULT_PLL_ARM_BYPASS         0
#define LPM_DSM_CFG_DEFAULT_PLL_528_BYPASS         0
#define LPM_DSM_CFG_DEFAULT_PLL_480_BYPASS         2
#define LPM_DSM_CFG_DEFAULT_ARM_VOLTAGE            1100
#define LPM_DSM_CFG_DEFAULT_SOC_VOLTAGE            1100
#define LPM_DSM_CFG_DEFAULT_PU_VOLTAGE             0
#define LPM_DSM_CFG_DEFAULT_DISPLAY_PG             1
#define LPM_DSM_CFG_DEFAULT_USE_RC_OSC             0

#define LPM_STANDBY_CFG_DEFAULT_LOW_POWER_MODE     STOP_MODE
#define LPM_STANDBY_CFG_DEFAULT_ARM_POWER_GATE_EN  1
#define LPM_STANDBY_CFG_DEFAULT_ARM_CLOCK_GATE_EN  1
#define LPM_STANDBY_CFG_DEFAULT_L2_POWER_GATE_EN   0
#define LPM_STANDBY_CFG_DEFAULT_SOC_RWB_EN         1
#define LPM_STANDBY_CFG_DEFAULT_OSC_POWER_DOWN_EN  0
#define LPM_STANDBY_CFG_DEFAULT_STANDBY_VOLTAGE_EN 1
#define LPM_STANDBY_CFG_DEFAULT_WEAK_2P5_EN        0
#define LPM_STANDBY_CFG_DEFAULT_RING_OSC_EN        1
#define LPM_STANDBY_CFG_DEFAULT_STOP_MODE_CONFIG   1
#define LPM_STANDBY_CFG_DEFAULT_RBC_EN             1
#define LPM_STANDBY_CFG_DEFAULT_OSC_COUNT          0xAF
#define LPM_STANDBY_CFG_DEFAULT_RBC_COUNT          0x20
#define LPM_STANDBY_CFG_DEFAULT_STBY_COUNT         0x3
#define LPM_STANDBY_CFG_DEFAULT_ARM_PUP_SW         0x3F
#define LPM_STANDBY_CFG_DEFAULT_ARM_PUP_SW2ISO     0x3F
#define LPM_STANDBY_CFG_DEFAULT_RC_OSC_EN          1
#define LPM_STANDBY_CFG_DEFAULT_RC_OSC_CG_OVERRIDE 0
#define LPM_STANDBY_CFG_DEFAULT_GPT_WAKEUP_EN      1
#define LPM_STANDBY_CFG_DEFAULT_GPT_WAKEUP_TIME_MS 500
#define LPM_STANDBY_CFG_DEFAULT_UART_WAKEUP_EN     1
#define LPM_STANDBY_CFG_DEFAULT_WAKEUP_LOOP        3
#define LPM_STANDBY_CFG_DEFAULT_DRAM_EN            GLOBAL_DRAM_EN
#define LPM_STANDBY_CFG_DEFAULT_L1_CACHE_EN        GLOBAL_L1_CACHE_EN
#define LPM_STANDBY_CFG_DEFAULT_L2_CACHE_EN        GLOBAL_L2_CACHE_EN
#define LPM_STANDBY_CFG_DEFAULT_ARM_CLOCK_FREQ     800
#define LPM_STANDBY_CFG_DEFAULT_BUS_CLOCK_FREQ     400
#define LPM_STANDBY_CFG_DEFAULT_PLL_ARM_BYPASS     0
#define LPM_STANDBY_CFG_DEFAULT_PLL_528_BYPASS     0
#define LPM_STANDBY_CFG_DEFAULT_PLL_480_BYPASS     2
#define LPM_STANDBY_CFG_DEFAULT_ARM_VOLTAGE        1100
#define LPM_STANDBY_CFG_DEFAULT_SOC_VOLTAGE        1100
#define LPM_STANDBY_CFG_DEFAULT_PU_VOLTAGE         0
#define LPM_STANDBY_CFG_DEFAULT_DISPLAY_PG         1
#define LPM_STANDBY_CFG_DEFAULT_USE_RC_OSC         0


#define LPM_STOP_CFG_DEFAULT_LOW_POWER_MODE        WAIT_MODE
#define LPM_STOP_CFG_DEFAULT_ARM_POWER_GATE_EN     0
#define LPM_STOP_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_STOP_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_STOP_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_STOP_CFG_DEFAULT_OSC_POWER_DOWN_EN     0
#define LPM_STOP_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_STOP_CFG_DEFAULT_WEAK_2P5_EN           0
#define LPM_STOP_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_STOP_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_STOP_CFG_DEFAULT_RBC_EN                0
#define LPM_STOP_CFG_DEFAULT_OSC_COUNT             0xAF
#define LPM_STOP_CFG_DEFAULT_RBC_COUNT             0x20
#define LPM_STOP_CFG_DEFAULT_STBY_COUNT            0x3
#define LPM_STOP_CFG_DEFAULT_ARM_PUP_SW            0x3F
#define LPM_STOP_CFG_DEFAULT_ARM_PUP_SW2ISO        0x3F
#define LPM_STOP_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_STOP_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_STOP_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_STOP_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    500
#define LPM_STOP_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_STOP_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_STOP_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_STOP_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_STOP_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_STOP_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_STOP_CFG_DEFAULT_BUS_CLOCK_FREQ        400
#define LPM_STOP_CFG_DEFAULT_PLL_ARM_BYPASS        2
#define LPM_STOP_CFG_DEFAULT_PLL_528_BYPASS        2
#define LPM_STOP_CFG_DEFAULT_PLL_480_BYPASS        2
#define LPM_STOP_CFG_DEFAULT_ARM_VOLTAGE           900
#define LPM_STOP_CFG_DEFAULT_SOC_VOLTAGE           1100
#define LPM_STOP_CFG_DEFAULT_PU_VOLTAGE            0
#define LPM_STOP_CFG_DEFAULT_DISPLAY_PG            1
#define LPM_STOP_CFG_DEFAULT_USE_RC_OSC            0

#define LPM_IDLE_CFG_DEFAULT_LOW_POWER_MODE        WAIT_MODE
#define LPM_IDLE_CFG_DEFAULT_ARM_POWER_GATE_EN     0
#define LPM_IDLE_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_IDLE_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_IDLE_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_IDLE_CFG_DEFAULT_OSC_POWER_DOWN_EN     0
#define LPM_IDLE_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_IDLE_CFG_DEFAULT_WEAK_2P5_EN           0
#define LPM_IDLE_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_IDLE_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_IDLE_CFG_DEFAULT_RBC_EN                0
#define LPM_IDLE_CFG_DEFAULT_OSC_COUNT             0xAF
#define LPM_IDLE_CFG_DEFAULT_RBC_COUNT             0x20
#define LPM_IDLE_CFG_DEFAULT_STBY_COUNT            0x3
#define LPM_IDLE_CFG_DEFAULT_ARM_PUP_SW            0x3F
#define LPM_IDLE_CFG_DEFAULT_ARM_PUP_SW2ISO        0x3F
#define LPM_IDLE_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_IDLE_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_IDLE_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_IDLE_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    500
#define LPM_IDLE_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_IDLE_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_IDLE_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_IDLE_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_IDLE_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_IDLE_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_IDLE_CFG_DEFAULT_BUS_CLOCK_FREQ        400
#define LPM_IDLE_CFG_DEFAULT_PLL_ARM_BYPASS        1
#define LPM_IDLE_CFG_DEFAULT_PLL_528_BYPASS        1
#define LPM_IDLE_CFG_DEFAULT_PLL_480_BYPASS        1
#define LPM_IDLE_CFG_DEFAULT_ARM_VOLTAGE           1100
#define LPM_IDLE_CFG_DEFAULT_SOC_VOLTAGE           1100
#define LPM_IDLE_CFG_DEFAULT_PU_VOLTAGE            1100
#define LPM_IDLE_CFG_DEFAULT_DISPLAY_PG            0
#define LPM_IDLE_CFG_DEFAULT_USE_RC_OSC            0

/* USE WAIT MODE FOR IDLE */
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_LOW_POWER_MODE        WAIT_MODE
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_POWER_GATE_EN     0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_OSC_POWER_DOWN_EN     0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_WEAK_2P5_EN           0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RBC_EN                0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_OSC_COUNT             0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RBC_COUNT             0x0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STBY_COUNT            0x0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_PUP_SW            0x1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_PUP_SW2ISO        0x2
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    1000
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_BUS_CLOCK_FREQ        400
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_ARM_BYPASS        2
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_528_BYPASS        2
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_480_BYPASS        2
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_VOLTAGE           1100
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_SOC_VOLTAGE           1100
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PU_VOLTAGE            0
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_DISPLAY_PG            1
#define LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_USE_RC_OSC            0

/* LAB126 IDLE MODE 1, WAIT MODE WITH ARM PG, NO ANALOG LOW POWER SETTINGS*/
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_LOW_POWER_MODE        WAIT_MODE
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_POWER_GATE_EN     1 // ARM PG
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_OSC_POWER_DOWN_EN     0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_WEAK_2P5_EN           0 // not only for weak2p5 but also used for other analog low power setting
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_RBC_EN                0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_OSC_COUNT             0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_RBC_COUNT             0x0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_STBY_COUNT            0x0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_PUP_SW            0x1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_PUP_SW2ISO        0x2
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    1000
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_BUS_CLOCK_FREQ        1 // LOW FREQ MODE, for both ARM & BUS
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_ARM_BYPASS        2
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_528_BYPASS        2
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_480_BYPASS        2
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_VOLTAGE           1100 // LDO Enabled Mode
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_SOC_VOLTAGE           1500 // LDO Bypass Mode
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_PU_VOLTAGE            0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_DISPLAY_PG            0
#define LPM_LAB126_IDLE_1_CFG_DEFAULT_USE_RC_OSC            0

/* LAB126 IDLE MODE 2, WAIT MODE WITHOUT ARM PG, USE ANALOG LOW POWER SETTINGS*/
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_LOW_POWER_MODE        WAIT_MODE
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_POWER_GATE_EN     0 // NO ARM PG
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_OSC_POWER_DOWN_EN     0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_WEAK_2P5_EN           1 // not only for weak2p5 but also used for other analog low power setting
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_RBC_EN                0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_OSC_COUNT             0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_RBC_COUNT             0x0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_STBY_COUNT            0x0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_PUP_SW            0x1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_PUP_SW2ISO        0x2
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    1000
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_BUS_CLOCK_FREQ        1 // LOW FREQ MODE, for both ARM & BUS
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_ARM_BYPASS        2
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_528_BYPASS        2
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_480_BYPASS        2
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_VOLTAGE           1500 // LDO Bypass Mode
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_SOC_VOLTAGE           1500 // LDO Bypass Mode
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_PU_VOLTAGE            0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_DISPLAY_PG            0
#define LPM_LAB126_IDLE_2_CFG_DEFAULT_USE_RC_OSC            0

/* USE STOP MODE FOR IDLE */
/* LDO ENABLE MODE */
#define LPM_LAB126_IDLE_CFG_DEFAULT_LOW_POWER_MODE        STOP_MODE
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_POWER_GATE_EN     1
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_CLOCK_GATE_EN     1
#define LPM_LAB126_IDLE_CFG_DEFAULT_L2_POWER_GATE_EN      0
#define LPM_LAB126_IDLE_CFG_DEFAULT_SOC_RWB_EN            0
#define LPM_LAB126_IDLE_CFG_DEFAULT_OSC_POWER_DOWN_EN     1
#define LPM_LAB126_IDLE_CFG_DEFAULT_STANDBY_VOLTAGE_EN    0
#define LPM_LAB126_IDLE_CFG_DEFAULT_WEAK_2P5_EN           0
#define LPM_LAB126_IDLE_CFG_DEFAULT_RING_OSC_EN           1
#define LPM_LAB126_IDLE_CFG_DEFAULT_STOP_MODE_CONFIG      0
#define LPM_LAB126_IDLE_CFG_DEFAULT_RBC_EN                0
#define LPM_LAB126_IDLE_CFG_DEFAULT_OSC_COUNT             0
#define LPM_LAB126_IDLE_CFG_DEFAULT_RBC_COUNT             0x0
#define LPM_LAB126_IDLE_CFG_DEFAULT_STBY_COUNT            0x0
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_PUP_SW            0x0
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_PUP_SW2ISO        0x2
#define LPM_LAB126_IDLE_CFG_DEFAULT_RC_OSC_EN             1
#define LPM_LAB126_IDLE_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    0
#define LPM_LAB126_IDLE_CFG_DEFAULT_GPT_WAKEUP_EN         1
#define LPM_LAB126_IDLE_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    1000
#define LPM_LAB126_IDLE_CFG_DEFAULT_UART_WAKEUP_EN        1
#define LPM_LAB126_IDLE_CFG_DEFAULT_WAKEUP_LOOP           3
#define LPM_LAB126_IDLE_CFG_DEFAULT_DRAM_EN               GLOBAL_DRAM_EN
#define LPM_LAB126_IDLE_CFG_DEFAULT_L1_CACHE_EN           GLOBAL_L1_CACHE_EN
#define LPM_LAB126_IDLE_CFG_DEFAULT_L2_CACHE_EN           GLOBAL_L2_CACHE_EN
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_CLOCK_FREQ        800
#define LPM_LAB126_IDLE_CFG_DEFAULT_BUS_CLOCK_FREQ        400
#define LPM_LAB126_IDLE_CFG_DEFAULT_PLL_ARM_BYPASS        0
#define LPM_LAB126_IDLE_CFG_DEFAULT_PLL_528_BYPASS        0
#define LPM_LAB126_IDLE_CFG_DEFAULT_PLL_480_BYPASS        2
#define LPM_LAB126_IDLE_CFG_DEFAULT_ARM_VOLTAGE           1200
#define LPM_LAB126_IDLE_CFG_DEFAULT_SOC_VOLTAGE           1500
#define LPM_LAB126_IDLE_CFG_DEFAULT_PU_VOLTAGE            0
#define LPM_LAB126_IDLE_CFG_DEFAULT_DISPLAY_PG            0
#define LPM_LAB126_IDLE_CFG_DEFAULT_USE_RC_OSC            1

/* USE STOP MODE FOR IDLE */
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_LOW_POWER_MODE         STOP_MODE
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_POWER_GATE_EN      1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_CLOCK_GATE_EN      1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_L2_POWER_GATE_EN       0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_SOC_RWB_EN             1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_OSC_POWER_DOWN_EN      1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_STANDBY_VOLTAGE_EN     1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_WEAK_2P5_EN            0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_RING_OSC_EN            1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_STOP_MODE_CONFIG       0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_RBC_EN                 1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_OSC_COUNT              0x2F
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_RBC_COUNT              11
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_STBY_COUNT             0x2
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_PUP_SW             0x2
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_PUP_SW2ISO         0x2
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_RC_OSC_EN              1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_RC_OSC_CG_OVERRIDE     0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_GPT_WAKEUP_EN          1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_GPT_WAKEUP_TIME_MS     1000
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_UART_WAKEUP_EN         1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_WAKEUP_LOOP            3
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_DRAM_EN                GLOBAL_DRAM_EN
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_L1_CACHE_EN            GLOBAL_L1_CACHE_EN
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_L2_CACHE_EN            GLOBAL_L2_CACHE_EN
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_CLOCK_FREQ         800
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_BUS_CLOCK_FREQ         400
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_ARM_BYPASS         0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_528_BYPASS         0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_480_BYPASS         2
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_VOLTAGE            1100
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_SOC_VOLTAGE            1100
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_PU_VOLTAGE             0
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_DISPLAY_PG             1
#define LPM_LAB126_SUSPEND_CFG_DEFAULT_USE_RC_OSC             0

#ifdef LPM_DEFAULT_DSM_MODE
#define LPM_TEST_MODE                         LPM_DSM_MODE
#define LPM_CFG_DEFAULT_LOW_POWER_MODE        LPM_DSM_CFG_DEFAULT_LOW_POWER_MODE
#define LPM_CFG_DEFAULT_ARM_POWER_GATE_EN     LPM_DSM_CFG_DEFAULT_ARM_POWER_GATE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN     LPM_DSM_CFG_DEFAULT_ARM_CLOCK_GATE_EN
#define LPM_CFG_DEFAULT_L2_POWER_GATE_EN      LPM_DSM_CFG_DEFAULT_L2_POWER_GATE_EN
#define LPM_CFG_DEFAULT_SOC_RWB_EN            LPM_DSM_CFG_DEFAULT_SOC_RWB_EN
#define LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN     LPM_DSM_CFG_DEFAULT_OSC_POWER_DOWN_EN
#define LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN    LPM_DSM_CFG_DEFAULT_STANDBY_VOLTAGE_EN
#define LPM_CFG_DEFAULT_WEAK_2P5_EN           LPM_DSM_CFG_DEFAULT_WEAK_2P5_EN
#define LPM_CFG_DEFAULT_RING_OSC_EN           LPM_DSM_CFG_DEFAULT_RING_OSC_EN
#define LPM_CFG_DEFAULT_STOP_MODE_CONFIG      LPM_DSM_CFG_DEFAULT_STOP_MODE_CONFIG
#define LPM_CFG_DEFAULT_RBC_EN                LPM_DSM_CFG_DEFAULT_RBC_EN
#define LPM_CFG_DEFAULT_OSC_COUNT             LPM_DSM_CFG_DEFAULT_OSC_COUNT
#define LPM_CFG_DEFAULT_RBC_COUNT             LPM_DSM_CFG_DEFAULT_RBC_COUNT
#define LPM_CFG_DEFAULT_STBY_COUNT            LPM_DSM_CFG_DEFAULT_STBY_COUNT
#define LPM_CFG_DEFAULT_ARM_PUP_SW            LPM_DSM_CFG_DEFAULT_ARM_PUP_SW
#define LPM_CFG_DEFAULT_ARM_PUP_SW2ISO        LPM_DSM_CFG_DEFAULT_ARM_PUP_SW2ISO
#define LPM_CFG_DEFAULT_RC_OSC_EN             LPM_DSM_CFG_DEFAULT_RC_OSC_EN
#define LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    LPM_DSM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE
#define LPM_CFG_DEFAULT_GPT_WAKEUP_EN         LPM_DSM_CFG_DEFAULT_GPT_WAKEUP_EN
#define LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    LPM_DSM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS
#define LPM_CFG_DEFAULT_UART_WAKEUP_EN        LPM_DSM_CFG_DEFAULT_UART_WAKEUP_EN
#define LPM_CFG_DEFAULT_WAKEUP_LOOP           LPM_DSM_CFG_DEFAULT_WAKEUP_LOOP
#define LPM_CFG_DEFAULT_DRAM_EN               LPM_DSM_CFG_DEFAULT_DRAM_EN
#define LPM_CFG_DEFAULT_L1_CACHE_EN           LPM_DSM_CFG_DEFAULT_L1_CACHE_EN
#define LPM_CFG_DEFAULT_L2_CACHE_EN           LPM_DSM_CFG_DEFAULT_L2_CACHE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_FREQ        LPM_DSM_CFG_DEFAULT_ARM_CLOCK_FREQ
#define LPM_CFG_DEFAULT_BUS_CLOCK_FREQ        LPM_DSM_CFG_DEFAULT_BUS_CLOCK_FREQ
#define LPM_CFG_DEFAULT_PLL_ARM_BYPASS        LPM_DSM_CFG_DEFAULT_PLL_ARM_BYPASS
#define LPM_CFG_DEFAULT_PLL_528_BYPASS        LPM_DSM_CFG_DEFAULT_PLL_528_BYPASS
#define LPM_CFG_DEFAULT_PLL_480_BYPASS        LPM_DSM_CFG_DEFAULT_PLL_480_BYPASS
#define LPM_CFG_DEFAULT_ARM_VOLTAGE           LPM_DSM_CFG_DEFAULT_ARM_VOLTAGE
#define LPM_CFG_DEFAULT_SOC_VOLTAGE           LPM_DSM_CFG_DEFAULT_SOC_VOLTAGE
#define LPM_CFG_DEFAULT_PU_VOLTAGE            LPM_DSM_CFG_DEFAULT_PU_VOLTAGE
#define LPM_CFG_DEFAULT_DISPLAY_PG            LPM_DSM_CFG_DEFAULT_DISPLAY_PG
#define LPM_CFG_DEFAULT_USE_RC_OSC            LPM_DSM_CFG_DEFAULT_USE_RC_OSC
#endif

#ifdef LPM_DEFAULT_STANDBY_MODE
#define LPM_TEST_MODE                         LPM_STANDBY_MODE
#define LPM_CFG_DEFAULT_LOW_POWER_MODE        LPM_STANDBY_CFG_DEFAULT_LOW_POWER_MODE
#define LPM_CFG_DEFAULT_ARM_POWER_GATE_EN     LPM_STANDBY_CFG_DEFAULT_ARM_POWER_GATE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN     LPM_STANDBY_CFG_DEFAULT_ARM_CLOCK_GATE_EN
#define LPM_CFG_DEFAULT_L2_POWER_GATE_EN      LPM_STANDBY_CFG_DEFAULT_L2_POWER_GATE_EN
#define LPM_CFG_DEFAULT_SOC_RWB_EN            LPM_STANDBY_CFG_DEFAULT_SOC_RWB_EN
#define LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN     LPM_STANDBY_CFG_DEFAULT_OSC_POWER_DOWN_EN
#define LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN    LPM_STANDBY_CFG_DEFAULT_STANDBY_VOLTAGE_EN
#define LPM_CFG_DEFAULT_WEAK_2P5_EN           LPM_STANDBY_CFG_DEFAULT_WEAK_2P5_EN
#define LPM_CFG_DEFAULT_RING_OSC_EN           LPM_STANDBY_CFG_DEFAULT_RING_OSC_EN
#define LPM_CFG_DEFAULT_STOP_MODE_CONFIG      LPM_STANDBY_CFG_DEFAULT_STOP_MODE_CONFIG
#define LPM_CFG_DEFAULT_RBC_EN                LPM_STANDBY_CFG_DEFAULT_RBC_EN
#define LPM_CFG_DEFAULT_OSC_COUNT             LPM_STANDBY_CFG_DEFAULT_OSC_COUNT
#define LPM_CFG_DEFAULT_RBC_COUNT             LPM_STANDBY_CFG_DEFAULT_RBC_COUNT
#define LPM_CFG_DEFAULT_STBY_COUNT            LPM_STANDBY_CFG_DEFAULT_STBY_COUNT
#define LPM_CFG_DEFAULT_ARM_PUP_SW            LPM_STANDBY_CFG_DEFAULT_ARM_PUP_SW
#define LPM_CFG_DEFAULT_ARM_PUP_SW2ISO        LPM_STANDBY_CFG_DEFAULT_ARM_PUP_SW2ISO
#define LPM_CFG_DEFAULT_RC_OSC_EN             LPM_STANDBY_CFG_DEFAULT_RC_OSC_EN
#define LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    LPM_STANDBY_CFG_DEFAULT_RC_OSC_CG_OVERRIDE
#define LPM_CFG_DEFAULT_GPT_WAKEUP_EN         LPM_STANDBY_CFG_DEFAULT_GPT_WAKEUP_EN
#define LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    LPM_STANDBY_CFG_DEFAULT_GPT_WAKEUP_TIME_MS
#define LPM_CFG_DEFAULT_UART_WAKEUP_EN        LPM_STANDBY_CFG_DEFAULT_UART_WAKEUP_EN
#define LPM_CFG_DEFAULT_WAKEUP_LOOP           LPM_STANDBY_CFG_DEFAULT_WAKEUP_LOOP
#define LPM_CFG_DEFAULT_DRAM_EN               LPM_STANDBY_CFG_DEFAULT_DRAM_EN
#define LPM_CFG_DEFAULT_L1_CACHE_EN           LPM_STANDBY_CFG_DEFAULT_L1_CACHE_EN
#define LPM_CFG_DEFAULT_L2_CACHE_EN           LPM_STANDBY_CFG_DEFAULT_L2_CACHE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_FREQ        LPM_STANDBY_CFG_DEFAULT_ARM_CLOCK_FREQ
#define LPM_CFG_DEFAULT_BUS_CLOCK_FREQ        LPM_STANDBY_CFG_DEFAULT_BUS_CLOCK_FREQ
#define LPM_CFG_DEFAULT_PLL_ARM_BYPASS        LPM_STANDBY_CFG_DEFAULT_PLL_ARM_BYPASS
#define LPM_CFG_DEFAULT_PLL_528_BYPASS        LPM_STANDBY_CFG_DEFAULT_PLL_528_BYPASS
#define LPM_CFG_DEFAULT_PLL_480_BYPASS        LPM_STANDBY_CFG_DEFAULT_PLL_480_BYPASS
#define LPM_CFG_DEFAULT_ARM_VOLTAGE           LPM_STANDBY_CFG_DEFAULT_ARM_VOLTAGE
#define LPM_CFG_DEFAULT_SOC_VOLTAGE           LPM_STANDBY_CFG_DEFAULT_SOC_VOLTAGE
#define LPM_CFG_DEFAULT_PU_VOLTAGE            LPM_STANDBY_CFG_DEFAULT_PU_VOLTAGE
#define LPM_CFG_DEFAULT_DISPLAY_PG            LPM_STANDBY_CFG_DEFAULT_DISPLAY_PG
#define LPM_CFG_DEFAULT_USE_RC_OSC            LPM_STANDBY_CFG_DEFAULT_USE_RC_OSC
#endif

#ifdef LPM_DEFAULT_STOP_MODE
#define LPM_TEST_MODE                         LPM_STOP_MODE
#define LPM_CFG_DEFAULT_LOW_POWER_MODE        LPM_STOP_CFG_DEFAULT_LOW_POWER_MODE
#define LPM_CFG_DEFAULT_ARM_POWER_GATE_EN     LPM_STOP_CFG_DEFAULT_ARM_POWER_GATE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN     LPM_STOP_CFG_DEFAULT_ARM_CLOCK_GATE_EN
#define LPM_CFG_DEFAULT_L2_POWER_GATE_EN      LPM_STOP_CFG_DEFAULT_L2_POWER_GATE_EN
#define LPM_CFG_DEFAULT_SOC_RWB_EN            LPM_STOP_CFG_DEFAULT_SOC_RWB_EN
#define LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN     LPM_STOP_CFG_DEFAULT_OSC_POWER_DOWN_EN
#define LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN    LPM_STOP_CFG_DEFAULT_STANDBY_VOLTAGE_EN
#define LPM_CFG_DEFAULT_WEAK_2P5_EN           LPM_STOP_CFG_DEFAULT_WEAK_2P5_EN
#define LPM_CFG_DEFAULT_RING_OSC_EN           LPM_STOP_CFG_DEFAULT_RING_OSC_EN
#define LPM_CFG_DEFAULT_STOP_MODE_CONFIG      LPM_STOP_CFG_DEFAULT_STOP_MODE_CONFIG
#define LPM_CFG_DEFAULT_RBC_EN                LPM_STOP_CFG_DEFAULT_RBC_EN
#define LPM_CFG_DEFAULT_OSC_COUNT             LPM_STOP_CFG_DEFAULT_OSC_COUNT
#define LPM_CFG_DEFAULT_RBC_COUNT             LPM_STOP_CFG_DEFAULT_RBC_COUNT
#define LPM_CFG_DEFAULT_STBY_COUNT            LPM_STOP_CFG_DEFAULT_STBY_COUNT
#define LPM_CFG_DEFAULT_ARM_PUP_SW            LPM_STOP_CFG_DEFAULT_ARM_PUP_SW
#define LPM_CFG_DEFAULT_ARM_PUP_SW2ISO        LPM_STOP_CFG_DEFAULT_ARM_PUP_SW2ISO
#define LPM_CFG_DEFAULT_RC_OSC_EN             LPM_STOP_CFG_DEFAULT_RC_OSC_EN
#define LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    LPM_STOP_CFG_DEFAULT_RC_OSC_CG_OVERRIDE
#define LPM_CFG_DEFAULT_GPT_WAKEUP_EN         LPM_STOP_CFG_DEFAULT_GPT_WAKEUP_EN
#define LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    LPM_STOP_CFG_DEFAULT_GPT_WAKEUP_TIME_MS
#define LPM_CFG_DEFAULT_UART_WAKEUP_EN        LPM_STOP_CFG_DEFAULT_UART_WAKEUP_EN
#define LPM_CFG_DEFAULT_WAKEUP_LOOP           LPM_STOP_CFG_DEFAULT_WAKEUP_LOOP
#define LPM_CFG_DEFAULT_DRAM_EN               LPM_STOP_CFG_DEFAULT_DRAM_EN
#define LPM_CFG_DEFAULT_L1_CACHE_EN           LPM_STOP_CFG_DEFAULT_L1_CACHE_EN
#define LPM_CFG_DEFAULT_L2_CACHE_EN           LPM_STOP_CFG_DEFAULT_L2_CACHE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_FREQ        LPM_STOP_CFG_DEFAULT_ARM_CLOCK_FREQ
#define LPM_CFG_DEFAULT_BUS_CLOCK_FREQ        LPM_STOP_CFG_DEFAULT_BUS_CLOCK_FREQ
#define LPM_CFG_DEFAULT_PLL_ARM_BYPASS        LPM_STOP_CFG_DEFAULT_PLL_ARM_BYPASS
#define LPM_CFG_DEFAULT_PLL_528_BYPASS        LPM_STOP_CFG_DEFAULT_PLL_528_BYPASS
#define LPM_CFG_DEFAULT_PLL_480_BYPASS        LPM_STOP_CFG_DEFAULT_PLL_480_BYPASS
#define LPM_CFG_DEFAULT_ARM_VOLTAGE           LPM_STOP_CFG_DEFAULT_ARM_VOLTAGE
#define LPM_CFG_DEFAULT_SOC_VOLTAGE           LPM_STOP_CFG_DEFAULT_SOC_VOLTAGE
#define LPM_CFG_DEFAULT_PU_VOLTAGE            LPM_STOP_CFG_DEFAULT_PU_VOLTAGE
#define LPM_CFG_DEFAULT_DISPLAY_PG            LPM_STOP_CFG_DEFAULT_DISPLAY_PG
#define LPM_CFG_DEFAULT_USE_RC_OSC            LPM_STOP_CFG_DEFAULT_USE_RC_OSC
#endif

#ifdef LPM_DEFAULT_IDLE_MODE
#define LPM_TEST_MODE                         LPM_IDLE_MODE
#define LPM_CFG_DEFAULT_LOW_POWER_MODE        LPM_IDLE_CFG_DEFAULT_LOW_POWER_MODE
#define LPM_CFG_DEFAULT_ARM_POWER_GATE_EN     LPM_IDLE_CFG_DEFAULT_ARM_POWER_GATE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN     LPM_IDLE_CFG_DEFAULT_ARM_CLOCK_GATE_EN
#define LPM_CFG_DEFAULT_L2_POWER_GATE_EN      LPM_IDLE_CFG_DEFAULT_L2_POWER_GATE_EN
#define LPM_CFG_DEFAULT_SOC_RWB_EN            LPM_IDLE_CFG_DEFAULT_SOC_RWB_EN
#define LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN     LPM_IDLE_CFG_DEFAULT_OSC_POWER_DOWN_EN
#define LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN    LPM_IDLE_CFG_DEFAULT_STANDBY_VOLTAGE_EN
#define LPM_CFG_DEFAULT_WEAK_2P5_EN           LPM_IDLE_CFG_DEFAULT_WEAK_2P5_EN
#define LPM_CFG_DEFAULT_RING_OSC_EN           LPM_IDLE_CFG_DEFAULT_RING_OSC_EN
#define LPM_CFG_DEFAULT_STOP_MODE_CONFIG      LPM_IDLE_CFG_DEFAULT_STOP_MODE_CONFIG
#define LPM_CFG_DEFAULT_RBC_EN                LPM_IDLE_CFG_DEFAULT_RBC_EN
#define LPM_CFG_DEFAULT_OSC_COUNT             LPM_IDLE_CFG_DEFAULT_OSC_COUNT
#define LPM_CFG_DEFAULT_RBC_COUNT             LPM_IDLE_CFG_DEFAULT_RBC_COUNT
#define LPM_CFG_DEFAULT_STBY_COUNT            LPM_IDLE_CFG_DEFAULT_STBY_COUNT
#define LPM_CFG_DEFAULT_ARM_PUP_SW            LPM_IDLE_CFG_DEFAULT_ARM_PUP_SW
#define LPM_CFG_DEFAULT_ARM_PUP_SW2ISO        LPM_IDLE_CFG_DEFAULT_ARM_PUP_SW2ISO
#define LPM_CFG_DEFAULT_RC_OSC_EN             LPM_IDLE_CFG_DEFAULT_RC_OSC_EN
#define LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE    LPM_IDLE_CFG_DEFAULT_RC_OSC_CG_OVERRIDE
#define LPM_CFG_DEFAULT_GPT_WAKEUP_EN         LPM_IDLE_CFG_DEFAULT_GPT_WAKEUP_EN
#define LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS    LPM_IDLE_CFG_DEFAULT_GPT_WAKEUP_TIME_MS
#define LPM_CFG_DEFAULT_UART_WAKEUP_EN        LPM_IDLE_CFG_DEFAULT_UART_WAKEUP_EN
#define LPM_CFG_DEFAULT_WAKEUP_LOOP           LPM_IDLE_CFG_DEFAULT_WAKEUP_LOOP
#define LPM_CFG_DEFAULT_DRAM_EN               LPM_IDLE_CFG_DEFAULT_DRAM_EN
#define LPM_CFG_DEFAULT_L1_CACHE_EN           LPM_IDLE_CFG_DEFAULT_L1_CACHE_EN
#define LPM_CFG_DEFAULT_L2_CACHE_EN           LPM_IDLE_CFG_DEFAULT_L2_CACHE_EN
#define LPM_CFG_DEFAULT_ARM_CLOCK_FREQ        LPM_IDLE_CFG_DEFAULT_ARM_CLOCK_FREQ
#define LPM_CFG_DEFAULT_BUS_CLOCK_FREQ        LPM_IDLE_CFG_DEFAULT_BUS_CLOCK_FREQ
#define LPM_CFG_DEFAULT_PLL_ARM_BYPASS        LPM_IDLE_CFG_DEFAULT_PLL_ARM_BYPASS
#define LPM_CFG_DEFAULT_PLL_528_BYPASS        LPM_IDLE_CFG_DEFAULT_PLL_528_BYPASS
#define LPM_CFG_DEFAULT_PLL_480_BYPASS        LPM_IDLE_CFG_DEFAULT_PLL_480_BYPASS
#define LPM_CFG_DEFAULT_ARM_VOLTAGE           LPM_IDLE_CFG_DEFAULT_ARM_VOLTAGE
#define LPM_CFG_DEFAULT_SOC_VOLTAGE           LPM_IDLE_CFG_DEFAULT_SOC_VOLTAGE
#define LPM_CFG_DEFAULT_PU_VOLTAGE            LPM_IDLE_CFG_DEFAULT_PU_VOLTAGE
#define LPM_CFG_DEFAULT_DISPLAY_PG            LPM_IDLE_CFG_DEFAULT_DISPLAY_PG
#define LPM_CFG_DEFAULT_USE_RC_OSC            LPM_IDLE_CFG_DEFAULT_USE_RC_OSC
#endif

#ifndef LPM_TEST_MODE
	#error("Default LPM mode not defined")
#endif

config_t lpm_config[] __attribute__ ((section (".low_power_data"))) =
{
 	{ LPM_CFG_ID_DRAM_EN           , "DRAM_EN            ", "", LPM_CFG_DEFAULT_DRAM_EN           , 0, 0, 0, NULL },
	{ LPM_CFG_ID_L1_CACHE_EN       , "L1_CACHE_EN        ", "", LPM_CFG_DEFAULT_L1_CACHE_EN       , 0, 0, 0, NULL },                        
	{ LPM_CFG_ID_L2_CACHE_EN       , "L2_CACHE_EN        ", "", LPM_CFG_DEFAULT_L2_CACHE_EN       , 0, 0, 0, NULL },      
	{ LPM_CFG_ID_ARM_CLOCK_FREQ    , "ARM_CLOCK_FREQ     ", "", LPM_CFG_DEFAULT_ARM_CLOCK_FREQ    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_BUS_CLOCK_FREQ    , "BUS_CLOCK_FREQ     ", "", LPM_CFG_DEFAULT_BUS_CLOCK_FREQ    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_PLL_ARM_BYPASS    , "PLL_ARM_BYPASS     ", "", LPM_CFG_DEFAULT_PLL_ARM_BYPASS    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_PLL_528_BYPASS    , "PLL_528_BYPASS     ", "", LPM_CFG_DEFAULT_PLL_528_BYPASS    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_PLL_480_BYPASS    , "PLL_480_BYPASS     ", "", LPM_CFG_DEFAULT_PLL_480_BYPASS    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_ARM_VOLTAGE       , "ARM_VOLTAGE        ", "", LPM_CFG_DEFAULT_ARM_VOLTAGE       , 0, 0, 0, NULL },
	{ LPM_CFG_ID_SOC_VOLTAGE       , "SOC_VOLTAGE        ", "", LPM_CFG_DEFAULT_SOC_VOLTAGE       , 0, 0, 0, NULL },
	{ LPM_CFG_ID_PU_VOLTAGE        , "PU_VOLTAGE         ", "", LPM_CFG_DEFAULT_PU_VOLTAGE        , 0, 0, 0, NULL },
	{ LPM_CFG_ID_DISPLAY_PG        , "DISPLAY_PG         ", "", LPM_CFG_DEFAULT_DISPLAY_PG        , 0, 0, 0, NULL }, 
	{ LPM_CFG_ID_USE_RC_OSC        , "USE_RC_OSC         ", "", LPM_CFG_DEFAULT_USE_RC_OSC        , 0, 0, 0, NULL },
	{ LPM_CFG_ID_LOW_POWER_MODE    , "LOW_POWER_MODE     ", "", LPM_CFG_DEFAULT_LOW_POWER_MODE    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_ARM_POWER_GATE_EN , "ARM_POWER_GATE_EN  ", "", LPM_CFG_DEFAULT_ARM_POWER_GATE_EN , 0, 0, 0, NULL },
	{ LPM_CFG_ID_ARM_CLOCK_GATE_EN , "ARM_CLOCK_GATE_EN  ", "", LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN , 0, 0, 0, NULL },
	{ LPM_CFG_ID_L2_POWER_GATE_EN  , "L2_POWER_GATE_EN   ", "", LPM_CFG_DEFAULT_L2_POWER_GATE_EN  , 0, 0, 0, NULL },
	{ LPM_CFG_ID_SOC_RWB_EN        , "SOC_RWB_EN         ", "", LPM_CFG_DEFAULT_SOC_RWB_EN        , 0, 0, 0, NULL },
	{ LPM_CFG_ID_OSC_POWER_DOWN_EN , "OSC_POWER_DOWN_EN  ", "", LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN , 0, 0, 0, NULL },
	{ LPM_CFG_ID_STANDBY_VOLTAGE_EN, "STANDBY_VOLTAGE_EN ", "", LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN, 0, 0, 0, NULL },
	{ LPM_CFG_ID_WEAK_2P5_EN       , "WEAK_2P5_EN        ", "", LPM_CFG_DEFAULT_WEAK_2P5_EN       , 0, 0, 0, NULL },
	{ LPM_CFG_ID_RING_OSC_EN       , "RING_OSC_EN        ", "", LPM_CFG_DEFAULT_RING_OSC_EN       , 0, 0, 0, NULL },
	{ LPM_CFG_ID_STOP_MODE_CONFIG  , "STOP_MODE_CONFIG   ", "", LPM_CFG_DEFAULT_STOP_MODE_CONFIG  , 0, 0, 0, NULL },
	{ LPM_CFG_ID_RBC_EN            , "RBC_EN             ", "", LPM_CFG_DEFAULT_RBC_EN            , 0, 0, 0, NULL },
	{ LPM_CFG_ID_OSC_COUNT         , "OSC_COUNT          ", "", LPM_CFG_DEFAULT_OSC_COUNT         , 0, 0, 0, NULL },
	{ LPM_CFG_ID_RBC_COUNT         , "RBC_COUNT          ", "", LPM_CFG_DEFAULT_RBC_COUNT         , 0, 0, 0, NULL },
	{ LPM_CFG_ID_STBY_COUNT        , "STBY_COUNT         ", "", LPM_CFG_DEFAULT_STBY_COUNT        , 0, 0, 0, NULL },
	{ LPM_CFG_ID_ARM_PUP_SW        , "ARM_PUP_SW         ", "", LPM_CFG_DEFAULT_ARM_PUP_SW        , 0, 0, 0, NULL },
	{ LPM_CFG_ID_ARM_PUP_SW2ISO    , "ARM_PUP_SW2ISO     ", "", LPM_CFG_DEFAULT_ARM_PUP_SW2ISO    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_RC_OSC_EN         , "RC_OSC_EN          ", "", LPM_CFG_DEFAULT_RC_OSC_EN         , 0, 0, 0, NULL },
	{ LPM_CFG_ID_RC_OSC_CG_OVERRIDE, "RC_OSC_CG_OVERRIDE ", "", LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE, 0, 0, 0, NULL },
	{ LPM_CFG_ID_GPT_WAKEUP_EN     , "GPT_WAKEUP_EN      ", "", LPM_CFG_DEFAULT_GPT_WAKEUP_EN     , 0, 0, 0, NULL },
	{ LPM_CFG_ID_GPT_WAKEUP_TIME_MS, "GPT_WAKEUP_TIME_MS ", "", LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS, 0, 0, 0, NULL },
	{ LPM_CFG_ID_UART_WAKEUP_EN    , "UART_WAKEUP_EN     ", "", LPM_CFG_DEFAULT_UART_WAKEUP_EN    , 0, 0, 0, NULL },
	{ LPM_CFG_ID_WAKEUP_LOOP       , "WAKEUP_LOOP        ", "", LPM_CFG_DEFAULT_WAKEUP_LOOP       , 0, 0, 0, NULL }
};

#ifdef CFG_FROM_DEFINE
#define DRAM_EN               LPM_CFG_DEFAULT_DRAM_EN
#define L1_CACHE_EN           LPM_CFG_DEFAULT_L1_CACHE_EN
#define L2_CACHE_EN           LPM_CFG_DEFAULT_L2_CACHE_EN
#define ARM_CLOCK_FREQ        LPM_CFG_DEFAULT_ARM_CLOCK_FREQ
#define BUS_CLOCK_FREQ        LPM_CFG_DEFAULT_BUS_CLOCK_FREQ
#define PLL_ARM_BYPASS        LPM_CFG_DEFAULT_PLL_ARM_BYPASS
#define PLL_528_BYPASS        LPM_CFG_DEFAULT_PLL_528_BYPASS
#define PLL_480_BYPASS        LPM_CFG_DEFAULT_PLL_480_BYPASS
#define ARM_VOLTAGE           LPM_CFG_DEFAULT_ARM_VOLTAGE
#define SOC_VOLTAGE           LPM_CFG_DEFAULT_SOC_VOLTAGE
#define PU_VOLTAGE            LPM_CFG_DEFAULT_PU_VOLTAGE
#define DISPLAY_PG            LPM_CFG_DEFAULT_DISPLAY_PG
#define USE_RC_OSC            LPM_CFG_DEFAULT_USE_RC_OSC
#define LOW_POWER_MODE        LPM_CFG_DEFAULT_LOW_POWER_MODE
#define ARM_POWER_GATE_EN     LPM_CFG_DEFAULT_ARM_POWER_GATE_EN
#define ARM_CLOCK_GATE_EN     LPM_CFG_DEFAULT_ARM_CLOCK_GATE_EN
#define L2_POWER_GATE_EN      LPM_CFG_DEFAULT_L2_POWER_GATE_EN
#define SOC_RWB_EN            LPM_CFG_DEFAULT_SOC_RWB_EN
#define OSC_POWER_DOWN_EN     LPM_CFG_DEFAULT_OSC_POWER_DOWN_EN
#define STANDBY_VOLTAGE_EN    LPM_CFG_DEFAULT_STANDBY_VOLTAGE_EN
#define WEAK_2P5_EN           LPM_CFG_DEFAULT_WEAK_2P5_EN
#define RING_OSC_EN           LPM_CFG_DEFAULT_RING_OSC_EN
#define STOP_MODE_CONFIG      LPM_CFG_DEFAULT_STOP_MODE_CONFIG
#define RBC_EN                LPM_CFG_DEFAULT_RBC_EN
#define OSC_COUNT             LPM_CFG_DEFAULT_OSC_COUNT
#define RBC_COUNT             LPM_CFG_DEFAULT_RBC_COUNT
#define STBY_COUNT            LPM_CFG_DEFAULT_STBY_COUNT
#define ARM_PUP_SW            LPM_CFG_DEFAULT_ARM_PUP_SW
#define ARM_PUP_SW2ISO        LPM_CFG_DEFAULT_ARM_PUP_SW2ISO
#define RC_OSC_EN             LPM_CFG_DEFAULT_RC_OSC_EN
#define RC_OSC_CG_OVERRIDE    LPM_CFG_DEFAULT_RC_OSC_CG_OVERRIDE
#define GPT_WAKEUP_EN         LPM_CFG_DEFAULT_GPT_WAKEUP_EN
#define GPT_WAKEUP_TIME_MS    LPM_CFG_DEFAULT_GPT_WAKEUP_TIME_MS
#define UART_WAKEUP_EN        LPM_CFG_DEFAULT_UART_WAKEUP_EN
#define WAKEUP_LOOP           LPM_CFG_DEFAULT_WAKEUP_LOOP
#else
#define DRAM_EN               (lpm_config[LPM_CFG_ID_DRAM_EN              ].parameter0)
#define L1_CACHE_EN           (lpm_config[LPM_CFG_ID_L1_CACHE_EN          ].parameter0)
#define L2_CACHE_EN           (lpm_config[LPM_CFG_ID_L2_CACHE_EN          ].parameter0)
#define ARM_CLOCK_FREQ        (lpm_config[LPM_CFG_ID_ARM_CLOCK_FREQ       ].parameter0)
#define BUS_CLOCK_FREQ        (lpm_config[LPM_CFG_ID_BUS_CLOCK_FREQ       ].parameter0)
#define PLL_ARM_BYPASS        (lpm_config[LPM_CFG_ID_PLL_ARM_BYPASS       ].parameter0)
#define PLL_528_BYPASS        (lpm_config[LPM_CFG_ID_PLL_528_BYPASS       ].parameter0)
#define PLL_480_BYPASS        (lpm_config[LPM_CFG_ID_PLL_480_BYPASS       ].parameter0)
#define ARM_VOLTAGE           (lpm_config[LPM_CFG_ID_ARM_VOLTAGE          ].parameter0)
#define SOC_VOLTAGE           (lpm_config[LPM_CFG_ID_SOC_VOLTAGE          ].parameter0)
#define PU_VOLTAGE            (lpm_config[LPM_CFG_ID_PU_VOLTAGE           ].parameter0)
#define DISPLAY_PG            (lpm_config[LPM_CFG_ID_DISPLAY_PG           ].parameter0)
#define USE_RC_OSC            (lpm_config[LPM_CFG_ID_USE_RC_OSC           ].parameter0)
#define LOW_POWER_MODE        (lpm_config[LPM_CFG_ID_LOW_POWER_MODE       ].parameter0)
#define ARM_POWER_GATE_EN     (lpm_config[LPM_CFG_ID_ARM_POWER_GATE_EN    ].parameter0)
#define ARM_CLOCK_GATE_EN     (lpm_config[LPM_CFG_ID_ARM_CLOCK_GATE_EN    ].parameter0)
#define L2_POWER_GATE_EN      (lpm_config[LPM_CFG_ID_L2_POWER_GATE_EN     ].parameter0)
#define SOC_RWB_EN            (lpm_config[LPM_CFG_ID_SOC_RWB_EN           ].parameter0)
#define OSC_POWER_DOWN_EN     (lpm_config[LPM_CFG_ID_OSC_POWER_DOWN_EN    ].parameter0)
#define STANDBY_VOLTAGE_EN    (lpm_config[LPM_CFG_ID_STANDBY_VOLTAGE_EN   ].parameter0)
#define WEAK_2P5_EN           (lpm_config[LPM_CFG_ID_WEAK_2P5_EN          ].parameter0)
#define RING_OSC_EN           (lpm_config[LPM_CFG_ID_RING_OSC_EN          ].parameter0)
#define STOP_MODE_CONFIG      (lpm_config[LPM_CFG_ID_STOP_MODE_CONFIG     ].parameter0)
#define RBC_EN                (lpm_config[LPM_CFG_ID_RBC_EN               ].parameter0)
#define OSC_COUNT             (lpm_config[LPM_CFG_ID_OSC_COUNT            ].parameter0)
#define RBC_COUNT             (lpm_config[LPM_CFG_ID_RBC_COUNT            ].parameter0)
#define STBY_COUNT            (lpm_config[LPM_CFG_ID_STBY_COUNT           ].parameter0)
#define ARM_PUP_SW            (lpm_config[LPM_CFG_ID_ARM_PUP_SW           ].parameter0)
#define ARM_PUP_SW2ISO        (lpm_config[LPM_CFG_ID_ARM_PUP_SW2ISO       ].parameter0)
#define RC_OSC_EN             (lpm_config[LPM_CFG_ID_RC_OSC_EN            ].parameter0)
#define RC_OSC_CG_OVERRIDE    (lpm_config[LPM_CFG_ID_RC_OSC_CG_OVERRIDE   ].parameter0)
#define GPT_WAKEUP_EN         (lpm_config[LPM_CFG_ID_GPT_WAKEUP_EN        ].parameter0)
#define GPT_WAKEUP_TIME_MS    (lpm_config[LPM_CFG_ID_GPT_WAKEUP_TIME_MS   ].parameter0)
#define UART_WAKEUP_EN        (lpm_config[LPM_CFG_ID_UART_WAKEUP_EN       ].parameter0)
#define WAKEUP_LOOP           (lpm_config[LPM_CFG_ID_WAKEUP_LOOP          ].parameter0)
#endif

// ---------------------------------------------------------------------
// functions
// ---------------------------------------------------------------------
void lpm_config_mode(unsigned int)
	__attribute__ ((section (".low_power_code")));
void lpm_config_mode(unsigned int mode)
{
	if(mode == LPM_LAB126_IDLE_MODE) {
		update_config(lpm_config + LPM_CFG_ID_DRAM_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_DRAM_EN);
		update_config(lpm_config + LPM_CFG_ID_L1_CACHE_EN     , LPM_LAB126_IDLE_CFG_DEFAULT_L1_CACHE_EN);
		update_config(lpm_config + LPM_CFG_ID_L2_CACHE_EN     , LPM_LAB126_IDLE_CFG_DEFAULT_L2_CACHE_EN);
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_FREQ    , LPM_LAB126_IDLE_CFG_DEFAULT_ARM_CLOCK_FREQ);
		update_config(lpm_config + LPM_CFG_ID_BUS_CLOCK_FREQ    , LPM_LAB126_IDLE_CFG_DEFAULT_BUS_CLOCK_FREQ);
		update_config(lpm_config + LPM_CFG_ID_PLL_ARM_BYPASS    , LPM_LAB126_IDLE_CFG_DEFAULT_PLL_ARM_BYPASS);
		update_config(lpm_config + LPM_CFG_ID_PLL_528_BYPASS    , LPM_LAB126_IDLE_CFG_DEFAULT_PLL_528_BYPASS);
		update_config(lpm_config + LPM_CFG_ID_PLL_480_BYPASS    , LPM_LAB126_IDLE_CFG_DEFAULT_PLL_480_BYPASS);
		update_config(lpm_config + LPM_CFG_ID_ARM_VOLTAGE    , LPM_LAB126_IDLE_CFG_DEFAULT_ARM_VOLTAGE);
		update_config(lpm_config + LPM_CFG_ID_SOC_VOLTAGE    , LPM_LAB126_IDLE_CFG_DEFAULT_SOC_VOLTAGE);
		update_config(lpm_config + LPM_CFG_ID_PU_VOLTAGE    , LPM_LAB126_IDLE_CFG_DEFAULT_PU_VOLTAGE);
		update_config(lpm_config + LPM_CFG_ID_DISPLAY_PG    , LPM_LAB126_IDLE_CFG_DEFAULT_DISPLAY_PG);
		update_config(lpm_config + LPM_CFG_ID_USE_RC_OSC    , LPM_LAB126_IDLE_CFG_DEFAULT_USE_RC_OSC);
		update_config(lpm_config + LPM_CFG_ID_LOW_POWER_MODE    , LPM_LAB126_IDLE_CFG_DEFAULT_LOW_POWER_MODE);
		update_config(lpm_config + LPM_CFG_ID_ARM_POWER_GATE_EN, LPM_LAB126_IDLE_CFG_DEFAULT_ARM_POWER_GATE_EN);
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_GATE_EN, LPM_LAB126_IDLE_CFG_DEFAULT_ARM_CLOCK_GATE_EN);
		update_config(lpm_config + LPM_CFG_ID_L2_POWER_GATE_EN  , LPM_LAB126_IDLE_CFG_DEFAULT_L2_POWER_GATE_EN  );
		update_config(lpm_config + LPM_CFG_ID_SOC_RWB_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_SOC_RWB_EN);
		update_config(lpm_config + LPM_CFG_ID_OSC_POWER_DOWN_EN, LPM_LAB126_IDLE_CFG_DEFAULT_OSC_POWER_DOWN_EN);
		update_config(lpm_config + LPM_CFG_ID_STANDBY_VOLTAGE_EN, LPM_LAB126_IDLE_CFG_DEFAULT_STANDBY_VOLTAGE_EN);
		update_config(lpm_config + LPM_CFG_ID_WEAK_2P5_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_WEAK_2P5_EN);
		update_config(lpm_config + LPM_CFG_ID_RING_OSC_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_RING_OSC_EN);
		update_config(lpm_config + LPM_CFG_ID_STOP_MODE_CONFIG  , LPM_LAB126_IDLE_CFG_DEFAULT_STOP_MODE_CONFIG  );
		update_config(lpm_config + LPM_CFG_ID_RBC_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_RBC_EN);
		update_config(lpm_config + LPM_CFG_ID_OSC_COUNT    , LPM_LAB126_IDLE_CFG_DEFAULT_OSC_COUNT);
		update_config(lpm_config + LPM_CFG_ID_RBC_COUNT    , LPM_LAB126_IDLE_CFG_DEFAULT_RBC_COUNT);
		update_config(lpm_config + LPM_CFG_ID_STBY_COUNT    , LPM_LAB126_IDLE_CFG_DEFAULT_STBY_COUNT);
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW    , LPM_LAB126_IDLE_CFG_DEFAULT_ARM_PUP_SW);
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW2ISO    , LPM_LAB126_IDLE_CFG_DEFAULT_ARM_PUP_SW2ISO);
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_RC_OSC_EN);
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_CG_OVERRIDE, LPM_LAB126_IDLE_CFG_DEFAULT_RC_OSC_CG_OVERRIDE);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_EN     , LPM_LAB126_IDLE_CFG_DEFAULT_GPT_WAKEUP_EN);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_TIME_MS, LPM_LAB126_IDLE_CFG_DEFAULT_GPT_WAKEUP_TIME_MS);
		update_config(lpm_config + LPM_CFG_ID_UART_WAKEUP_EN    , LPM_LAB126_IDLE_CFG_DEFAULT_UART_WAKEUP_EN);
		update_config(lpm_config + LPM_CFG_ID_WAKEUP_LOOP    , LPM_LAB126_IDLE_CFG_DEFAULT_WAKEUP_LOOP);
	}

	if (mode == LPM_LAB126_IDLE_WAIT_MODE) {
		update_config(lpm_config + LPM_CFG_ID_DRAM_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_DRAM_EN           );
		update_config(lpm_config + LPM_CFG_ID_L1_CACHE_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L1_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_L2_CACHE_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L2_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_FREQ    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_BUS_CLOCK_FREQ    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_BUS_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_PLL_ARM_BYPASS    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_ARM_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_528_BYPASS    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_528_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_480_BYPASS    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PLL_480_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_ARM_VOLTAGE    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_SOC_VOLTAGE    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_SOC_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_PU_VOLTAGE    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_PU_VOLTAGE        );
		update_config(lpm_config + LPM_CFG_ID_DISPLAY_PG    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_DISPLAY_PG        );
		update_config(lpm_config + LPM_CFG_ID_USE_RC_OSC    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_USE_RC_OSC        );
		update_config(lpm_config + LPM_CFG_ID_LOW_POWER_MODE    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_LOW_POWER_MODE    );
		update_config(lpm_config + LPM_CFG_ID_ARM_POWER_GATE_EN, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_POWER_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_GATE_EN, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_CLOCK_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_L2_POWER_GATE_EN  , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_L2_POWER_GATE_EN  );
		update_config(lpm_config + LPM_CFG_ID_SOC_RWB_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_SOC_RWB_EN        );
		update_config(lpm_config + LPM_CFG_ID_OSC_POWER_DOWN_EN, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_OSC_POWER_DOWN_EN );
		update_config(lpm_config + LPM_CFG_ID_STANDBY_VOLTAGE_EN, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STANDBY_VOLTAGE_EN);
		update_config(lpm_config + LPM_CFG_ID_WEAK_2P5_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_WEAK_2P5_EN       );
		update_config(lpm_config + LPM_CFG_ID_RING_OSC_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RING_OSC_EN       );
		update_config(lpm_config + LPM_CFG_ID_STOP_MODE_CONFIG  , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STOP_MODE_CONFIG  );
		update_config(lpm_config + LPM_CFG_ID_RBC_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RBC_EN            );
		update_config(lpm_config + LPM_CFG_ID_OSC_COUNT    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_OSC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_RBC_COUNT    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RBC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_STBY_COUNT    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_STBY_COUNT        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_PUP_SW        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW2ISO    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_ARM_PUP_SW2ISO    );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RC_OSC_EN         );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_CG_OVERRIDE, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_RC_OSC_CG_OVERRIDE);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_GPT_WAKEUP_EN     );
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_TIME_MS, LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_GPT_WAKEUP_TIME_MS);
		update_config(lpm_config + LPM_CFG_ID_UART_WAKEUP_EN    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_UART_WAKEUP_EN    );
		update_config(lpm_config + LPM_CFG_ID_WAKEUP_LOOP    , LPM_LAB126_IDLE_WAIT_CFG_DEFAULT_WAKEUP_LOOP       );
	}

	if (mode == LPM_LAB126_IDLE_1_MODE) {
		update_config(lpm_config + LPM_CFG_ID_DRAM_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_DRAM_EN           );
		update_config(lpm_config + LPM_CFG_ID_L1_CACHE_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_L1_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_L2_CACHE_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_L2_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_FREQ    , LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_BUS_CLOCK_FREQ    , LPM_LAB126_IDLE_1_CFG_DEFAULT_BUS_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_PLL_ARM_BYPASS    , LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_ARM_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_528_BYPASS    , LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_528_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_480_BYPASS    , LPM_LAB126_IDLE_1_CFG_DEFAULT_PLL_480_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_ARM_VOLTAGE    , LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_SOC_VOLTAGE    , LPM_LAB126_IDLE_1_CFG_DEFAULT_SOC_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_PU_VOLTAGE    , LPM_LAB126_IDLE_1_CFG_DEFAULT_PU_VOLTAGE        );
		update_config(lpm_config + LPM_CFG_ID_DISPLAY_PG    , LPM_LAB126_IDLE_1_CFG_DEFAULT_DISPLAY_PG        );
		update_config(lpm_config + LPM_CFG_ID_USE_RC_OSC    , LPM_LAB126_IDLE_1_CFG_DEFAULT_USE_RC_OSC        );
		update_config(lpm_config + LPM_CFG_ID_LOW_POWER_MODE    , LPM_LAB126_IDLE_1_CFG_DEFAULT_LOW_POWER_MODE    );
		update_config(lpm_config + LPM_CFG_ID_ARM_POWER_GATE_EN, LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_POWER_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_GATE_EN, LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_CLOCK_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_L2_POWER_GATE_EN  , LPM_LAB126_IDLE_1_CFG_DEFAULT_L2_POWER_GATE_EN  );
		update_config(lpm_config + LPM_CFG_ID_SOC_RWB_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_SOC_RWB_EN        );
		update_config(lpm_config + LPM_CFG_ID_OSC_POWER_DOWN_EN, LPM_LAB126_IDLE_1_CFG_DEFAULT_OSC_POWER_DOWN_EN );
		update_config(lpm_config + LPM_CFG_ID_STANDBY_VOLTAGE_EN, LPM_LAB126_IDLE_1_CFG_DEFAULT_STANDBY_VOLTAGE_EN);
		update_config(lpm_config + LPM_CFG_ID_WEAK_2P5_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_WEAK_2P5_EN       );
		update_config(lpm_config + LPM_CFG_ID_RING_OSC_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_RING_OSC_EN       );
		update_config(lpm_config + LPM_CFG_ID_STOP_MODE_CONFIG  , LPM_LAB126_IDLE_1_CFG_DEFAULT_STOP_MODE_CONFIG  );
		update_config(lpm_config + LPM_CFG_ID_RBC_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_RBC_EN            );
		update_config(lpm_config + LPM_CFG_ID_OSC_COUNT    , LPM_LAB126_IDLE_1_CFG_DEFAULT_OSC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_RBC_COUNT    , LPM_LAB126_IDLE_1_CFG_DEFAULT_RBC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_STBY_COUNT    , LPM_LAB126_IDLE_1_CFG_DEFAULT_STBY_COUNT        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW    , LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_PUP_SW        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW2ISO    , LPM_LAB126_IDLE_1_CFG_DEFAULT_ARM_PUP_SW2ISO    );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_RC_OSC_EN         );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_CG_OVERRIDE, LPM_LAB126_IDLE_1_CFG_DEFAULT_RC_OSC_CG_OVERRIDE);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_GPT_WAKEUP_EN     );
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_TIME_MS, LPM_LAB126_IDLE_1_CFG_DEFAULT_GPT_WAKEUP_TIME_MS);
		update_config(lpm_config + LPM_CFG_ID_UART_WAKEUP_EN    , LPM_LAB126_IDLE_1_CFG_DEFAULT_UART_WAKEUP_EN    );
		update_config(lpm_config + LPM_CFG_ID_WAKEUP_LOOP    , LPM_LAB126_IDLE_1_CFG_DEFAULT_WAKEUP_LOOP       );
	}

	if (mode == LPM_LAB126_IDLE_2_MODE) {
		update_config(lpm_config + LPM_CFG_ID_DRAM_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_DRAM_EN           );
		update_config(lpm_config + LPM_CFG_ID_L1_CACHE_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_L1_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_L2_CACHE_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_L2_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_FREQ    , LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_BUS_CLOCK_FREQ    , LPM_LAB126_IDLE_2_CFG_DEFAULT_BUS_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_PLL_ARM_BYPASS    , LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_ARM_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_528_BYPASS    , LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_528_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_480_BYPASS    , LPM_LAB126_IDLE_2_CFG_DEFAULT_PLL_480_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_ARM_VOLTAGE    , LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_SOC_VOLTAGE    , LPM_LAB126_IDLE_2_CFG_DEFAULT_SOC_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_PU_VOLTAGE    , LPM_LAB126_IDLE_2_CFG_DEFAULT_PU_VOLTAGE        );
		update_config(lpm_config + LPM_CFG_ID_DISPLAY_PG    , LPM_LAB126_IDLE_2_CFG_DEFAULT_DISPLAY_PG        );
		update_config(lpm_config + LPM_CFG_ID_USE_RC_OSC    , LPM_LAB126_IDLE_2_CFG_DEFAULT_USE_RC_OSC        );
		update_config(lpm_config + LPM_CFG_ID_LOW_POWER_MODE    , LPM_LAB126_IDLE_2_CFG_DEFAULT_LOW_POWER_MODE    );
		update_config(lpm_config + LPM_CFG_ID_ARM_POWER_GATE_EN, LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_POWER_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_GATE_EN, LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_CLOCK_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_L2_POWER_GATE_EN  , LPM_LAB126_IDLE_2_CFG_DEFAULT_L2_POWER_GATE_EN  );
		update_config(lpm_config + LPM_CFG_ID_SOC_RWB_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_SOC_RWB_EN        );
		update_config(lpm_config + LPM_CFG_ID_OSC_POWER_DOWN_EN, LPM_LAB126_IDLE_2_CFG_DEFAULT_OSC_POWER_DOWN_EN );
		update_config(lpm_config + LPM_CFG_ID_STANDBY_VOLTAGE_EN, LPM_LAB126_IDLE_2_CFG_DEFAULT_STANDBY_VOLTAGE_EN);
		update_config(lpm_config + LPM_CFG_ID_WEAK_2P5_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_WEAK_2P5_EN       );
		update_config(lpm_config + LPM_CFG_ID_RING_OSC_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_RING_OSC_EN       );
		update_config(lpm_config + LPM_CFG_ID_STOP_MODE_CONFIG  , LPM_LAB126_IDLE_2_CFG_DEFAULT_STOP_MODE_CONFIG  );
		update_config(lpm_config + LPM_CFG_ID_RBC_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_RBC_EN            );
		update_config(lpm_config + LPM_CFG_ID_OSC_COUNT    , LPM_LAB126_IDLE_2_CFG_DEFAULT_OSC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_RBC_COUNT    , LPM_LAB126_IDLE_2_CFG_DEFAULT_RBC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_STBY_COUNT    , LPM_LAB126_IDLE_2_CFG_DEFAULT_STBY_COUNT        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW    , LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_PUP_SW        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW2ISO    , LPM_LAB126_IDLE_2_CFG_DEFAULT_ARM_PUP_SW2ISO    );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_RC_OSC_EN         );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_CG_OVERRIDE, LPM_LAB126_IDLE_2_CFG_DEFAULT_RC_OSC_CG_OVERRIDE);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_GPT_WAKEUP_EN     );
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_TIME_MS, LPM_LAB126_IDLE_2_CFG_DEFAULT_GPT_WAKEUP_TIME_MS);
		update_config(lpm_config + LPM_CFG_ID_UART_WAKEUP_EN    , LPM_LAB126_IDLE_2_CFG_DEFAULT_UART_WAKEUP_EN    );
		update_config(lpm_config + LPM_CFG_ID_WAKEUP_LOOP    , LPM_LAB126_IDLE_2_CFG_DEFAULT_WAKEUP_LOOP       );
	}

	if(mode == LPM_LAB126_SUSPEND_MODE) {
		update_config(lpm_config + LPM_CFG_ID_DRAM_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_DRAM_EN           );
		update_config(lpm_config + LPM_CFG_ID_L1_CACHE_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_L1_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_L2_CACHE_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_L2_CACHE_EN       );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_FREQ    , LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_BUS_CLOCK_FREQ    , LPM_LAB126_SUSPEND_CFG_DEFAULT_BUS_CLOCK_FREQ    );
		update_config(lpm_config + LPM_CFG_ID_PLL_ARM_BYPASS    , LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_ARM_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_528_BYPASS    , LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_528_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_PLL_480_BYPASS    , LPM_LAB126_SUSPEND_CFG_DEFAULT_PLL_480_BYPASS    );
		update_config(lpm_config + LPM_CFG_ID_ARM_VOLTAGE    , LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_SOC_VOLTAGE    , LPM_LAB126_SUSPEND_CFG_DEFAULT_SOC_VOLTAGE       );
		update_config(lpm_config + LPM_CFG_ID_PU_VOLTAGE    , LPM_LAB126_SUSPEND_CFG_DEFAULT_PU_VOLTAGE        );
		update_config(lpm_config + LPM_CFG_ID_DISPLAY_PG    , LPM_LAB126_SUSPEND_CFG_DEFAULT_DISPLAY_PG        );
		update_config(lpm_config + LPM_CFG_ID_USE_RC_OSC    , LPM_LAB126_SUSPEND_CFG_DEFAULT_USE_RC_OSC        );
		update_config(lpm_config + LPM_CFG_ID_LOW_POWER_MODE    , LPM_LAB126_SUSPEND_CFG_DEFAULT_LOW_POWER_MODE    );
		update_config(lpm_config + LPM_CFG_ID_ARM_POWER_GATE_EN, LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_POWER_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_ARM_CLOCK_GATE_EN, LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_CLOCK_GATE_EN );
		update_config(lpm_config + LPM_CFG_ID_L2_POWER_GATE_EN  , LPM_LAB126_SUSPEND_CFG_DEFAULT_L2_POWER_GATE_EN  );
		update_config(lpm_config + LPM_CFG_ID_SOC_RWB_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_SOC_RWB_EN        );
		update_config(lpm_config + LPM_CFG_ID_OSC_POWER_DOWN_EN, LPM_LAB126_SUSPEND_CFG_DEFAULT_OSC_POWER_DOWN_EN );
		update_config(lpm_config + LPM_CFG_ID_STANDBY_VOLTAGE_EN, LPM_LAB126_SUSPEND_CFG_DEFAULT_STANDBY_VOLTAGE_EN);
		update_config(lpm_config + LPM_CFG_ID_WEAK_2P5_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_WEAK_2P5_EN       );
		update_config(lpm_config + LPM_CFG_ID_RING_OSC_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_RING_OSC_EN       );
		update_config(lpm_config + LPM_CFG_ID_STOP_MODE_CONFIG  , LPM_LAB126_SUSPEND_CFG_DEFAULT_STOP_MODE_CONFIG  );
		update_config(lpm_config + LPM_CFG_ID_RBC_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_RBC_EN            );
		update_config(lpm_config + LPM_CFG_ID_OSC_COUNT    , LPM_LAB126_SUSPEND_CFG_DEFAULT_OSC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_RBC_COUNT    , LPM_LAB126_SUSPEND_CFG_DEFAULT_RBC_COUNT         );
		update_config(lpm_config + LPM_CFG_ID_STBY_COUNT    , LPM_LAB126_SUSPEND_CFG_DEFAULT_STBY_COUNT        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW    , LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_PUP_SW        );
		update_config(lpm_config + LPM_CFG_ID_ARM_PUP_SW2ISO    , LPM_LAB126_SUSPEND_CFG_DEFAULT_ARM_PUP_SW2ISO    );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_RC_OSC_EN         );
		update_config(lpm_config + LPM_CFG_ID_RC_OSC_CG_OVERRIDE, LPM_LAB126_SUSPEND_CFG_DEFAULT_RC_OSC_CG_OVERRIDE);
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_GPT_WAKEUP_EN     );
		update_config(lpm_config + LPM_CFG_ID_GPT_WAKEUP_TIME_MS, LPM_LAB126_SUSPEND_CFG_DEFAULT_GPT_WAKEUP_TIME_MS);
		update_config(lpm_config + LPM_CFG_ID_UART_WAKEUP_EN    , LPM_LAB126_SUSPEND_CFG_DEFAULT_UART_WAKEUP_EN    );
		update_config(lpm_config + LPM_CFG_ID_WAKEUP_LOOP    , LPM_LAB126_SUSPEND_CFG_DEFAULT_WAKEUP_LOOP       );
    }
}

void load_system_lpm_config(void)
	__attribute__ ((section (".low_power_code")));
void load_system_lpm_config(void)
{
	system_config[SYS_CFG_ID_DRAM_EN  ].parameter1 = lpm_config[LPM_CFG_ID_DRAM_EN  ].parameter0;
	system_config[SYS_CFG_ID_L1_CACHE_EN  ].parameter1 = lpm_config[LPM_CFG_ID_L1_CACHE_EN  ].parameter0;
	system_config[SYS_CFG_ID_L2_CACHE_EN  ].parameter1 = lpm_config[LPM_CFG_ID_L2_CACHE_EN].parameter0;
	system_config[SYS_CFG_ID_ARM_CLOCK_FREQ].parameter1 = lpm_config[LPM_CFG_ID_ARM_CLOCK_FREQ    ].parameter0;
	system_config[SYS_CFG_ID_BUS_CLOCK_FREQ].parameter1 = lpm_config[LPM_CFG_ID_BUS_CLOCK_FREQ    ].parameter0;
	system_config[SYS_CFG_ID_PLL_ARM_BYPASS].parameter1 = lpm_config[LPM_CFG_ID_PLL_ARM_BYPASS    ].parameter0;
	system_config[SYS_CFG_ID_PLL_528_BYPASS].parameter1 = lpm_config[LPM_CFG_ID_PLL_528_BYPASS    ].parameter0;
	system_config[SYS_CFG_ID_PLL_480_BYPASS].parameter1 = lpm_config[LPM_CFG_ID_PLL_480_BYPASS    ].parameter0;
	system_config[SYS_CFG_ID_ARM_VOLTAGE  ].parameter1 = lpm_config[LPM_CFG_ID_ARM_VOLTAGE].parameter0;
	system_config[SYS_CFG_ID_SOC_VOLTAGE  ].parameter1 = lpm_config[LPM_CFG_ID_SOC_VOLTAGE].parameter0;
	system_config[SYS_CFG_ID_PU_VOLTAGE  ].parameter1 = lpm_config[LPM_CFG_ID_PU_VOLTAGE].parameter0;
	system_config[SYS_CFG_ID_DISPLAY_PG  ].parameter1 = lpm_config[LPM_CFG_ID_DISPLAY_PG].parameter0;
	system_config[SYS_CFG_ID_USE_RC_OSC  ].parameter1 = lpm_config[LPM_CFG_ID_USE_RC_OSC].parameter0;
}

// ---------------------------------------------------------------------
// main
// ---------------------------------------------------------------------
void lpm_disable_phys (void)
	__attribute__ ((section (".low_power_code")));
void lpm_disable_phys(void)
{
	// power down USB PHY
	reg32_write(0x020C9000,0xFFFFFFFF);
	reg32_write(0x020CA000,0xFFFFFFFF);
}

void lpm_disable_unused_clocks (void)
	__attribute__ ((section (".low_power_code")));
void lpm_disable_unused_clocks(void)
{
	// Clear CCGR
	reg32_write(CCM_BASE_ADDR + CCM_CCGR0_OFFSET, 0x00400005);
	reg32_write(CCM_BASE_ADDR + CCM_CCGR1_OFFSET, 0x00500000);
	reg32_write(CCM_BASE_ADDR + CCM_CCGR2_OFFSET, 0x00150000);
	//MMDC core clk=ON always except stop mode
	reg32_write(CCM_BASE_ADDR + CCM_CCGR3_OFFSET, 0x11F00000);	
	reg32_write(CCM_BASE_ADDR + CCM_CCGR4_OFFSET, 0x00004100);
	reg32_write(CCM_BASE_ADDR + CCM_CCGR5_OFFSET, 0x05001001);
	reg32_write(CCM_BASE_ADDR + CCM_CCGR6_OFFSET, 0x00000000);
	reg32_write(CCM_BASE_ADDR + CCM_CCGR7_OFFSET, 0x00000000);
}

void lpm_analog_low_power_setting (void)
	__attribute__ ((section (".low_power_code")));
void lpm_analog_low_power_setting(void)
{
	// enable FET odrive
	reg32_write(ANATOP_BASE_ADDR + 0x140,reg32_read(ANATOP_BASE_ADDR + 0x140) | 0x20000000);

	// configure RC OSC
	reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) | 0x0000000E);
}

void lpm_enet_setting (void)
	__attribute__ ((section (".low_power_code")));
void lpm_enet_setting(void)
{
	// Power down enet pll
	reg32_write(ANATOP_BASE_ADDR + 0x0E0, reg32_read(ANATOP_BASE_ADDR + 0x0E0) | (0x00001000));
}

void lpm_disable_pfds (void)
	__attribute__ ((section (".low_power_code")));
void lpm_disable_pfds(void)
{
	// shut off all PFDs on 480MHz PLL
	reg32_write(0x020C80F0, reg32_read(0x020C80F0) | 0x80808080);

	// shut off all PFDs on 528MHz PLL only expect 400MPFD
	reg32_write(0x020C8100, reg32_read(0x020C8100) | 0x80008080);
}

void lpm_pu_isolation_enable (void)
	__attribute__ ((section (".low_power_code")));
void lpm_pu_isolation_enable(void)
{
	// Enable PU Power Down
	reg32_write(GPC_BASE_ADDR + GPC_PGC_GPU_PGCR_OFFSET, 0x1);
	// Request PU Power Down
	reg32_write(GPC_BASE_ADDR + GPC_CNTR_OFFSET, 0x1);
}

void lpm_perclk_config (void)
	__attribute__ ((section (".low_power_code")));
void lpm_perclk_config(void)
{
	// select OSC as the peripheral clock
	reg32setbit(CCM_CSCMR1,6);

	// set perclk to 1MHz
	//reg32_write(CCM_CSCMR1, reg32_read(CCM_CSCMR1)&(~0x3F)|(0x17));
}

void lpm_config_init (void)
	__attribute__ ((section (".low_power_code")));
void lpm_config_init(void)
{
	lpm_pu_isolation_enable();
	lpm_disable_phys();
	lpm_disable_unused_clocks();
	lpm_analog_low_power_setting();
	lpm_enet_setting();
	lpm_disable_pfds();
	lpm_perclk_config();
}

void lpm_enter_exit (void)
	__attribute__ ((section (".low_power_code")));
void lpm_enter_exit(void)
{
	WORD data32;

	// Configure 2P5 LDO to enable weak 2P5
	if (WEAK_2P5_EN)
		reg32_write(ANATOP_BASE_ADDR + 0x130, reg32_read(ANATOP_BASE_ADDR + 0x130) | 0x40000);
	else
		reg32_write(ANATOP_BASE_ADDR + 0x130, reg32_read(ANATOP_BASE_ADDR + 0x130) & (~0x40000));

	// Enable Ring OSC, which also disable the path from VDDHIGH_IN to VDDSNVS_IN
	if (RING_OSC_EN)
		reg32_write(ANATOP_BASE_ADDR + 0x150, reg32_read(ANATOP_BASE_ADDR + 0x150) | 0x00002000);
	else
		reg32_write(ANATOP_BASE_ADDR + 0x150, reg32_read(ANATOP_BASE_ADDR + 0x150) & (~0x00002000));

	// RCOSC CLKGATE
	if (RC_OSC_CG_OVERRIDE)
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) | 0x00002000);
	else
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) & (~0x00002000));

	// RCOSC EN
	if (RC_OSC_EN)
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) | 0x00000001);
	else
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) & (~0x00000001));

	reg32_write(ANATOP_BASE_ADDR + 0x150, (reg32_read(ANATOP_BASE_ADDR + 0x150) & (~0x00001800)) | (STOP_MODE_CONFIG<<11));

	// Setup stop mode
	data32 = 0;
	data32 = word_field_wr(data32, LOW_POWER_MODE, 0,  2); // LPM=stop_mode
	data32 = word_field_wr(data32, ARM_CLOCK_GATE_EN, 5,  1); // ARM clock disable on WAIT
	data32 = word_field_wr(data32, OSC_POWER_DOWN_EN, 6,  1); // OSC Power Down in stop mode
	data32 = word_field_wr(data32, STANDBY_VOLTAGE_EN, 8,  1); // VSTBY
	data32 = word_field_wr(data32, SOC_RWB_EN, 16, 1); // WB for SoC
	data32 = word_field_wr(data32, 0, 17, 1); // WB for ARM
	data32 = word_field_wr(data32, STBY_COUNT,  9, 2); // Standby counter = 3

	data32 = word_field_wr(data32, 0x0, 7, 1); // OSC disable in run mode = 0
	data32 = word_field_wr(data32, 0x1, 2, 1); // Bypass pmic ready = 0 (don't care since pmic_ready is tie to 1
	data32 = word_field_wr(data32, 0x3, 3, 2); // Reserved 2'b11

	if((reg32_read(CCM_CLPCR) & 0x00000800) == 0x00000800)
		data32 = word_field_wr(data32,0x1,  11, 1); // OSC Power Down in run mode = 0
	else
		data32 = word_field_wr(data32,0x0,  11, 1); // OSC Power Down in run mode = 0

	if(DRAM_EN)
		data32 = word_field_wr(data32,0x0,  21, 1); // Bypass mmdc ch1 handshake = 0
	else
		data32 = word_field_wr(data32,0x1,  21, 1); // Bypass mmdc ch1 handshake = 1

	data32 = word_field_wr(data32, 0x1, 19, 1); // Bypass mmdc ch0 handshake = 1
	data32 = word_field_wr(data32, 0x0, 22, 1); // Mask Core0 WFI = 0
	data32 = word_field_wr(data32, 0x1, 23, 1); // Mask Core1 WFI = 1
	data32 = word_field_wr(data32, 0x1, 24, 1); // Mask Core2 WFI = 2
	data32 = word_field_wr(data32, 0x1, 25, 1); // Mask Core3 WFI = 3
	data32 = word_field_wr(data32, 0x0, 26, 1); // Mask SCU IDLE = 0
	data32 = word_field_wr(data32, 0x1, 27, 1); // Mask L2CC IDLE = 0
	reg32_write(CCM_BASE_ADDR + CCM_CLPCR_OFFSET, data32);

	// Set RBC
	data32 = 0;
	data32 = word_field_wr(data32, 0x0, 27, 1); // RBC_EN = 0
	data32 = word_field_wr(data32, 0x0, 21, 6); // RBC_COUNT = 0
	data32 = word_field_wr(data32, 0x1, 12, 1); // COSC_EN = 1
	data32 = word_field_wr(data32, OSC_COUNT, 0, 8); // OSC_CNT = 0xFF
	reg32_write(CCM_BASE_ADDR + CCM_CCR_OFFSET, data32);

	if (ARM_POWER_GATE_EN) {
		// Enable Power Gate CPU in LPM
		reg32_write(GPC_BASE_ADDR + GPC_PGC_CPU_PGCR_OFFSET, 0x1);
		reg32_write(GPC_BASE_ADDR + GPC_PGC_CPU_PUPSCR_OFFSET, 0xFFFF0000 | (ARM_PUP_SW) | (ARM_PUP_SW2ISO << 8));
		reg32_write(GPC_BASE_ADDR + GPC_PGC_CPU_PDNSCR_OFFSET, 0xFFFFFFFF);

		// Enable Power Gating for L2 Cache (For Test Only)
		if(L2_POWER_GATE_EN)
			reg32_write(GPC_BASE_ADDR+ GPC_CNTR_OFFSET, reg32_read(GPC_BASE_ADDR+ GPC_CNTR_OFFSET) | 0x00400000);
		else
			reg32_write(GPC_BASE_ADDR+ GPC_CNTR_OFFSET, reg32_read(GPC_BASE_ADDR+ GPC_CNTR_OFFSET) & (~0x00400000));

	} else {
		// Disable Power Gate CPU in LPM
		reg32_write(GPC_BASE_ADDR + GPC_PGC_CPU_PGCR_OFFSET, 0x0);
		// Disable Power Gate L2 in LPM
		reg32_write(GPC_BASE_ADDR+ GPC_CNTR_OFFSET, reg32_read(GPC_BASE_ADDR+ GPC_CNTR_OFFSET) & (~0x00400000));
	}

	// SCU standby enable
	reg32setbit(SCU_BASE_ADDR + SCU_CNTRL_OFFSET, 5);

	// Mask all wakeup event
	reg32_write(GPC_BASE_ADDR + GPC_IMR1_OFFSET, 0xFFFFFFFF); // 31:0
	reg32_write(GPC_BASE_ADDR + GPC_IMR2_OFFSET, 0xFFFFFFFF); // 63:32
	reg32_write(GPC_BASE_ADDR + GPC_IMR3_OFFSET, 0xFFFFFFFF); // 95:64
	reg32_write(GPC_BASE_ADDR + GPC_IMR4_OFFSET, 0xFFFFFFFF); //127:96

	// Update system setting according to lpm settings
	load_system_lpm_config();
	system_enter_lpm();

	/* Just access the MMDC, ANATOP, CCM and GPIO
	 registers before DRAM is put into self-refresh. 
	 To prime the TLBs.
	*/
	data32 = reg32_read(ANATOP_BASE_ADDR + 0x0);
	data32 = reg32_read(CCM_BASE_ADDR + 0x0);
	data32 = reg32_read(MMDC_P0_BASE_ADDR + 0x0);
	data32 = reg32_read(GPIO3_BASE_ADDR + 0x0);

	if(DRAM_EN &&  !ARM_POWER_GATE_EN)
		dram_enter_lpm();

	if (WEAK_2P5_EN && !ARM_POWER_GATE_EN) {
		/* Disable 1p1 brown out. */
		//ldr     r6, [r3, #0x110]
		//bic     r6, r6, #0x2
		//str     r6, [r3, #0x110]
		reg32_write(ANATOP_BASE_ADDR + 0x110, reg32_read(ANATOP_BASE_ADDR + 0x110) & (~0x2));

		/* Disable 3p0 brown out. */
		//ldr     r6, [r3, #0x120]
		//bic     r6, r6, #0x2
		//str     r6, [r3, #0x120]
		reg32_write(ANATOP_BASE_ADDR + 0x120, reg32_read(ANATOP_BASE_ADDR + 0x120) & (~0x2));

		/* Enable the weak 2P5 */
		//ldr     r6, [r3, #0x130]
		//orr    r6, r6, #0x40000
		//str     r6, [r3, #0x130]
		reg32_write(ANATOP_BASE_ADDR + 0x130, reg32_read(ANATOP_BASE_ADDR + 0x130) | 0x40000);

		/*Disable main 2p5. */
		//ldr     r6, [r3, #0x130]
		//bic    r6, r6, #0x1
		//str     r6, [r3, #0x130]
		reg32_write(ANATOP_BASE_ADDR + 0x130, reg32_read(ANATOP_BASE_ADDR + 0x130) & (~0x1));

		/* Disable 2p5 brown out. */
		//ldr     r6, [r3, #0x130]
		//bic     r6, r6, #0x2
		//str     r6, [r3, #0x130]
		reg32_write(ANATOP_BASE_ADDR + 0x130, reg32_read(ANATOP_BASE_ADDR + 0x130) & (~0x2));

		/* Enable low power bandgap */
		//ldr     r6, [r3, #0x260]
		//orr     r6, r6, #0x20
		//str     r6, [r3, #0x260]
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) | 0x20);

		/* turn off the bias current
		 * from the regular bandgap.
		 */
		//ldr     r6, [r3, #0x260]
		//orr     r6, r6, #0x80
		//str     r6, [r3, #0x260]
		reg32_write(ANATOP_BASE_ADDR + 0x260, reg32_read(ANATOP_BASE_ADDR + 0x260) | 0x80);

		/* Clear the REFTOP_SELFBIASOFF,
		 * self-bias circuit of the band gap.
		 * Per RM, should be cleared when
		 * band gap is powered down.
		 */
		//ldr     r6, [r3, #0x150]
		//bic     r6, r6, #0x8
		//str     r6, [r3, #0x150]
		reg32_write(ANATOP_BASE_ADDR + 0x150, reg32_read(ANATOP_BASE_ADDR + 0x150) & (~0x8));

		/*Power down the regular bandgap. */
		//ldr     r6, [r3, #0x150]
		//orr     r6, r6, #0x1
		//str     r6, [r3, #0x150]
		reg32_write(ANATOP_BASE_ADDR + 0x150, reg32_read(ANATOP_BASE_ADDR + 0x150) | 0x1);

		/* Reduce the OSC bias current. */
		reg32_write(ANATOP_BASE_ADDR + 0x150, reg32_read(ANATOP_BASE_ADDR + 0x150) | 0xC000);
	}

	if (SOC_RWB_EN)
		// Set RWB counter
		reg32_write(CCM_BASE_ADDR + CCM_CCR_OFFSET, reg32_read(CCM_BASE_ADDR + CCM_CCR_OFFSET) | (WB_COUNT << 16));

	// Set RWB EN
	reg32_write(CCM_BASE_ADDR + CCM_CLPCR_OFFSET, (reg32_read(CCM_BASE_ADDR + CCM_CLPCR_OFFSET) & (~(0x1 << 16))) | (SOC_RWB_EN << 16));

	if(RBC_EN)
		// Set RBC counter
		reg32_write(CCM_BASE_ADDR + CCM_CCR_OFFSET, reg32_read(CCM_BASE_ADDR + CCM_CCR_OFFSET) | (RBC_COUNT << 21));

	// Set RBC EN
	reg32_write(CCM_BASE_ADDR + CCM_CCR_OFFSET, (reg32_read(CCM_BASE_ADDR + CCM_CCR_OFFSET) & (~(0x1<<27))) | (RBC_EN << 27));

	// Clear a GPIO flag
	reg32_write(GPIO3_DR,reg32_read(GPIO3_DR) & (~0x00800000));

	// Enter WFI
	if (ARM_POWER_GATE_EN) {
		if (BUS_CLOCK_FREQ == 1)
			(*mx6q_suspend_t)(4,SUSPEND_OCRAM_PADDR,SUSPEND_OCRAM_BASE);
		else
			(*mx6q_suspend_t)(3,SUSPEND_OCRAM_PADDR,SUSPEND_OCRAM_BASE);
	} else {
		if(BUS_CLOCK_FREQ == 1)
			(*mx6q_suspend_t)(2,SUSPEND_OCRAM_PADDR,SUSPEND_OCRAM_BASE);
		else
			(*mx6q_suspend_t)(1,SUSPEND_OCRAM_PADDR,SUSPEND_OCRAM_BASE);
	}
	
	mx6q_suspend(4,SUSPEND_OCRAM_PADDR,SUSPEND_OCRAM_BASE);
}
