#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_FSL_MX6SL_LPM_TEST) += suspend_resume.o
obj-$(CONFIG_FSL_MX6SL_LPM_TEST) += test_entry.o \
  				   common_api.o \
				   config.o \
				   dram_api.o \
				   low_power_mode.o \
				   system_config.o 
