/*
 * Copyright (C) 2010-2012 Freescale Semiconductor, Inc.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

// This file lists instances offset memory location

//DDR LOGIC
#define MDCTL_OFFSET	0x00
#define MDPDC_OFFSET	0x04
#define MDOTC_OFFSET	0x08
#define MDCFG0_OFFSET	0x0C
#define MDCFG1_OFFSET	0x10
#define MDCFG2_OFFSET	0x14
#define MDMISC_OFFSET	0x18
#define MDSCR_OFFSET	0x1C
#define MDREF_OFFSET	0x20
#define MDWCC_OFFSET	0x24
#define MDRCC_OFFSET	0x28
#define MDRWD_OFFSET	0x2C
#define MDOR_OFFSET	    0x30
#define MDMRR_OFFSET	0x34
#define MDCFG3LP_OFFSET	0x38
#define MDMR4_OFFSET	0x3C
#define MDASP_OFFSET	0x40

//DDR_PHY
#define PHY_BASE_ADDR  0x800
#define MPZQHWCTRL_OFFSET   PHY_BASE_ADDR + 0x00
#define MPZQSWCTRL_OFFSET   PHY_BASE_ADDR + 0x04
#define MPWLGCR_OFFSET      PHY_BASE_ADDR + 0x08
#define MPWLDECTRL0_OFFSET  PHY_BASE_ADDR + 0x0C
#define MPWLDECTRL1_OFFSET  PHY_BASE_ADDR + 0x10
#define MPWLDLST_OFFSET     PHY_BASE_ADDR + 0x14
#define MPODTCTRL_OFFSET    PHY_BASE_ADDR + 0x18
#define MPREDQBY0DL_OFFSET  PHY_BASE_ADDR + 0x1C
#define MPREDQBY1DL_OFFSET  PHY_BASE_ADDR + 0x20
#define MPREDQBY2DL_OFFSET  PHY_BASE_ADDR + 0x24
#define MPREDQBY3DL_OFFSET  PHY_BASE_ADDR + 0x28
#define MPWRDQBY0DL_OFFSET  PHY_BASE_ADDR + 0x2C
#define MPWRDQBY1DL_OFFSET  PHY_BASE_ADDR + 0x30
#define MPWRDQBY2DL_OFFSET  PHY_BASE_ADDR + 0x34
#define MPWRDQBY3DL_OFFSET  PHY_BASE_ADDR + 0x38
#define MPDGCTRL0_OFFSET    PHY_BASE_ADDR + 0x3C
#define MPDGCTRL1_OFFSET    PHY_BASE_ADDR + 0x40
#define MPDGDLST_OFFSET     PHY_BASE_ADDR + 0x44
#define MPRDDLCTL_OFFSET    PHY_BASE_ADDR + 0x48
#define MPRDDLST_OFFSET     PHY_BASE_ADDR + 0x4C
#define MPWRDLCTL_OFFSET    PHY_BASE_ADDR + 0x50
#define MPWRDLST_OFFSET     PHY_BASE_ADDR + 0x54
#define MPSDCTRL_OFFSET     PHY_BASE_ADDR + 0x58
#define MPZQLP2CTL_OFFSET   PHY_BASE_ADDR + 0x5C
#define MPRDDLHWCTL_OFFSET  PHY_BASE_ADDR + 0x60
#define MPWRDLHWCTL_OFFSET  PHY_BASE_ADDR + 0x64
#define MPRDDLHWST0_OFFSET  PHY_BASE_ADDR + 0x68
#define MPRDDLHWST1_OFFSET  PHY_BASE_ADDR + 0x6C
#define MPWRDLHWST0_OFFSET  PHY_BASE_ADDR + 0x70
#define MPWRDLHWST1_OFFSET  PHY_BASE_ADDR + 0x74
#define MPWLHWERR_OFFSET    PHY_BASE_ADDR + 0x78
#define MPDGHWST0_OFFSET    PHY_BASE_ADDR + 0x7C
#define MPDGHWST1_OFFSET    PHY_BASE_ADDR + 0x80
#define MPDGHWST2_OFFSET    PHY_BASE_ADDR + 0x84
#define MPDGHWST3_OFFSET    PHY_BASE_ADDR + 0x88
#define MPPDCMPR1_OFFSET    PHY_BASE_ADDR + 0x8C
#define MPPDCMPR2_OFFSET    PHY_BASE_ADDR + 0x90
#define MPSWDAR_OFFSET      PHY_BASE_ADDR + 0x94
#define MPSWDRDR0_OFFSET    PHY_BASE_ADDR + 0x98
#define MPSWDRDR1_OFFSET    PHY_BASE_ADDR + 0x9C
#define MPSWDRDR2_OFFSET    PHY_BASE_ADDR + 0xA0
#define MPSWDRDR3_OFFSET    PHY_BASE_ADDR + 0xA4
#define MPSWDRDR4_OFFSET    PHY_BASE_ADDR + 0xA8
#define MPSWDRDR5_OFFSET    PHY_BASE_ADDR + 0xAC
#define MPSWDRDR6_OFFSET    PHY_BASE_ADDR + 0xB0
#define MPSWDRDR7_OFFSET    PHY_BASE_ADDR + 0xB4
#define MPMUR_OFFSET        PHY_BASE_ADDR + 0xB8
#define MPWRCADL_OFFSET     PHY_BASE_ADDR + 0xBC
#define MPDCCR_OFFSET       PHY_BASE_ADDR + 0xC0
#define MPBC_OFFSET         PHY_BASE_ADDR + 0xC4

//#########################################
#define GPIO3_DR            GPIO3_BASE_ADDR + 0x00
#define GPIO3_GDIR          GPIO3_BASE_ADDR + 0x04

//#########################################
//# GPC - updated B06116 - 10/12/2007
//#########################################

// GPC
#define GPC_CNTR_OFFSET	0x0
#define GPC_PGR_OFFSET	0x4
#define GPC_IMR1_OFFSET	0x8
#define GPC_IMR2_OFFSET	0xc
#define GPC_IMR3_OFFSET	0x10
#define GPC_IMR4_OFFSET	0x14
#define GPC_ISR1_OFFSET	0x18
#define GPC_ISR2_OFFSET	0x1c
#define GPC_ISR3_OFFSET	0x20
#define GPC_ISR4_OFFSET	0x24

#define GPC_PGC_GPU_PGCR_OFFSET   0x260
#define GPC_PGC_CPU_PGCR_OFFSET   0x2A0
#define GPC_PGC_CPU_PUPSCR_OFFSET 0x2A4
#define GPC_PGC_CPU_PDNSCR_OFFSET 0x2A8
#define GPC_PGC_CPU_PGSR_OFFSET   0x2Ac
//#########################################
//# CCM
//#########################################
#define CCM_CCR_OFFSET  0x00
#define CCM_CCDR_OFFSET 0x04
#define CCM_CSR_OFFSET  0x08
#define CCM_CCSR_OFFSET 0x0C
#define CCM_CACRR_OFFSET        0x10
#define CCM_CBCDR_OFFSET        0x14
#define CCM_CBCMR_OFFSET 0X18
#define CCM_CSCMR1_OFFSET 0x1c
#define CCM_CSCMR2_OFFSET 0x20
#define CCM_CSCDR1_OFFSET 0x24
#define CCM_CS1CDR_OFFSET 0x28
#define CCM_CS2CDR_OFFSET 0x2c
#define CCM_CDCDR_OFFSET 0x30
#define CCM_CHSCCDR_OFFSET 0x34
#define CCM_CSCDR2_OFFSET 0x38
#define CCM_CSCDR3_OFFSET 0x3c
#define CCM_CSCDR4_OFFSET 0x40
#define CCM_CWDR_OFFSET   0x44
#define CCM_CDHIPR_OFFSET 0x48
#define CCM_CDCR_OFFSET   0x4c
#define CCM_CTOR_OFFSET   0x50
#define CCM_CLPCR_OFFSET  0x54
#define CCM_CISR_OFFSET 0x58
#define CCM_CIMR_OFFSET 0x5c
#define CCM_CCOSR_OFFSET 0x60
#define CCM_CGPR_OFFSET 0x64
#define CCM_CCGR0_OFFSET 0x68
#define CCM_CCGR1_OFFSET 0x6c
#define CCM_CCGR2_OFFSET 0x70
#define CCM_CCGR3_OFFSET 0x74
#define CCM_CCGR4_OFFSET 0x78
#define CCM_CCGR5_OFFSET 0x7c
#define CCM_CCGR6_OFFSET 0x80
#define CCM_CCGR7_OFFSET 0x84
#define CCM_CMEOR_OFFSET 0x88

#define CCM_CCR     CCM_BASE_ADDR + CCM_CCR_OFFSET
#define CCM_CCDR    CCM_BASE_ADDR + CCM_CCDR_OFFSET
#define CCM_CSR     CCM_BASE_ADDR + CCM_CSR_OFFSET
#define CCM_CCSR    CCM_BASE_ADDR + CCM_CCSR_OFFSET
#define CCM_CACRR   CCM_BASE_ADDR + CCM_CACRR_OFFSET
#define CCM_CBCDR   CCM_BASE_ADDR + CCM_CBCDR_OFFSET
#define CCM_CBCMR   CCM_BASE_ADDR + CCM_CBCMR_OFFSET
#define CCM_CSCMR1  CCM_BASE_ADDR + CCM_CSCMR1_OFFSET
#define CCM_CSCMR2  CCM_BASE_ADDR + CCM_CSCMR2_OFFSET
#define CCM_CSCDR1  CCM_BASE_ADDR + CCM_CSCDR1_OFFSET
#define CCM_CS1CDR  CCM_BASE_ADDR + CCM_CS1CDR_OFFSET
#define CCM_CS2CDR  CCM_BASE_ADDR + CCM_CS2CDR_OFFSET
#define CCM_CDCDR   CCM_BASE_ADDR + CCM_CDCDR_OFFSET
#define CCM_CHSCCDR CCM_BASE_ADDR + CCM_CHSCCDR_OFFSET
#define CCM_CSCDR2  CCM_BASE_ADDR + CCM_CSCDR2_OFFSET
#define CCM_CSCDR3  CCM_BASE_ADDR + CCM_CSCDR3_OFFSET
#define CCM_CSCDR4  CCM_BASE_ADDR + CCM_CSCDR4_OFFSET
#define CCM_CWDR    CCM_BASE_ADDR + CCM_CWDR_OFFSET
#define CCM_CDHIPR  CCM_BASE_ADDR + CCM_CDHIPR_OFFSET
#define CCM_CDCR    CCM_BASE_ADDR + CCM_CDCR_OFFSET
#define CCM_CTOR    CCM_BASE_ADDR + CCM_CTOR_OFFSET
#define CCM_CLPCR   CCM_BASE_ADDR + CCM_CLPCR_OFFSET
#define CCM_CISR    CCM_BASE_ADDR + CCM_CISR_OFFSET
#define CCM_CIMR    CCM_BASE_ADDR + CCM_CIMR_OFFSET
#define CCM_CCOSR   CCM_BASE_ADDR + CCM_CCOSR_OFFSET
#define CCM_CGPR    CCM_BASE_ADDR + CCM_CGPR_OFFSET
#define CCM_CCGR0   CCM_BASE_ADDR + CCM_CCGR0_OFFSET
#define CCM_CCGR1   CCM_BASE_ADDR + CCM_CCGR1_OFFSET
#define CCM_CCGR2   CCM_BASE_ADDR + CCM_CCGR2_OFFSET
#define CCM_CCGR3   CCM_BASE_ADDR + CCM_CCGR3_OFFSET
#define CCM_CCGR4   CCM_BASE_ADDR + CCM_CCGR4_OFFSET
#define CCM_CCGR5   CCM_BASE_ADDR + CCM_CCGR5_OFFSET
#define CCM_CCGR6   CCM_BASE_ADDR + CCM_CCGR6_OFFSET
#define CCM_CCGR7   CCM_BASE_ADDR + CCM_CCGR7_OFFSET
#define CCM_CMEOR   CCM_BASE_ADDR + CCM_CMEOR_OFFSET
